/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tsinghua.thrift.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-05-29")
public class DataPermission implements org.apache.thrift.TBase<DataPermission, DataPermission._Fields>, java.io.Serializable, Cloneable, Comparable<DataPermission> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DataPermission");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField OWNER_FIELD_DESC = new org.apache.thrift.protocol.TField("owner", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TABLE_PREFIX_FIELD_DESC = new org.apache.thrift.protocol.TField("tablePrefix", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField TIMESTAMP_SET_FIELD_DESC = new org.apache.thrift.protocol.TField("timestampSet", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField IS_PUBLIC_FIELD_DESC = new org.apache.thrift.protocol.TField("isPublic", org.apache.thrift.protocol.TType.BOOL, (short)5);
  private static final org.apache.thrift.protocol.TField VISIBLE_USERS_FIELD_DESC = new org.apache.thrift.protocol.TField("visibleUsers", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DataPermissionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DataPermissionTupleSchemeFactory();

  public long id; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String owner; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String tablePrefix; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String timestampSet; // optional
  public boolean isPublic; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String visibleUsers; // optional
  public long createTime; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    OWNER((short)2, "owner"),
    TABLE_PREFIX((short)3, "tablePrefix"),
    TIMESTAMP_SET((short)4, "timestampSet"),
    IS_PUBLIC((short)5, "isPublic"),
    VISIBLE_USERS((short)6, "visibleUsers"),
    CREATE_TIME((short)7, "createTime");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // OWNER
          return OWNER;
        case 3: // TABLE_PREFIX
          return TABLE_PREFIX;
        case 4: // TIMESTAMP_SET
          return TIMESTAMP_SET;
        case 5: // IS_PUBLIC
          return IS_PUBLIC;
        case 6: // VISIBLE_USERS
          return VISIBLE_USERS;
        case 7: // CREATE_TIME
          return CREATE_TIME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __ISPUBLIC_ISSET_ID = 1;
  private static final int __CREATETIME_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.OWNER,_Fields.TABLE_PREFIX,_Fields.TIMESTAMP_SET,_Fields.VISIBLE_USERS,_Fields.CREATE_TIME};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.OWNER, new org.apache.thrift.meta_data.FieldMetaData("owner", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TABLE_PREFIX, new org.apache.thrift.meta_data.FieldMetaData("tablePrefix", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TIMESTAMP_SET, new org.apache.thrift.meta_data.FieldMetaData("timestampSet", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IS_PUBLIC, new org.apache.thrift.meta_data.FieldMetaData("isPublic", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.VISIBLE_USERS, new org.apache.thrift.meta_data.FieldMetaData("visibleUsers", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DataPermission.class, metaDataMap);
  }

  public DataPermission() {
  }

  public DataPermission(
    long id,
    boolean isPublic)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.isPublic = isPublic;
    setIsPublicIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DataPermission(DataPermission other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetOwner()) {
      this.owner = other.owner;
    }
    if (other.isSetTablePrefix()) {
      this.tablePrefix = other.tablePrefix;
    }
    if (other.isSetTimestampSet()) {
      this.timestampSet = other.timestampSet;
    }
    this.isPublic = other.isPublic;
    if (other.isSetVisibleUsers()) {
      this.visibleUsers = other.visibleUsers;
    }
    this.createTime = other.createTime;
  }

  @Override
  public DataPermission deepCopy() {
    return new DataPermission(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.owner = null;
    this.tablePrefix = null;
    this.timestampSet = null;
    setIsPublicIsSet(false);
    this.isPublic = false;
    this.visibleUsers = null;
    setCreateTimeIsSet(false);
    this.createTime = 0;
  }

  public long getId() {
    return this.id;
  }

  public DataPermission setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOwner() {
    return this.owner;
  }

  public DataPermission setOwner(@org.apache.thrift.annotation.Nullable java.lang.String owner) {
    this.owner = owner;
    return this;
  }

  public void unsetOwner() {
    this.owner = null;
  }

  /** Returns true if field owner is set (has been assigned a value) and false otherwise */
  public boolean isSetOwner() {
    return this.owner != null;
  }

  public void setOwnerIsSet(boolean value) {
    if (!value) {
      this.owner = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTablePrefix() {
    return this.tablePrefix;
  }

  public DataPermission setTablePrefix(@org.apache.thrift.annotation.Nullable java.lang.String tablePrefix) {
    this.tablePrefix = tablePrefix;
    return this;
  }

  public void unsetTablePrefix() {
    this.tablePrefix = null;
  }

  /** Returns true if field tablePrefix is set (has been assigned a value) and false otherwise */
  public boolean isSetTablePrefix() {
    return this.tablePrefix != null;
  }

  public void setTablePrefixIsSet(boolean value) {
    if (!value) {
      this.tablePrefix = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTimestampSet() {
    return this.timestampSet;
  }

  public DataPermission setTimestampSet(@org.apache.thrift.annotation.Nullable java.lang.String timestampSet) {
    this.timestampSet = timestampSet;
    return this;
  }

  public void unsetTimestampSet() {
    this.timestampSet = null;
  }

  /** Returns true if field timestampSet is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestampSet() {
    return this.timestampSet != null;
  }

  public void setTimestampSetIsSet(boolean value) {
    if (!value) {
      this.timestampSet = null;
    }
  }

  public boolean isIsPublic() {
    return this.isPublic;
  }

  public DataPermission setIsPublic(boolean isPublic) {
    this.isPublic = isPublic;
    setIsPublicIsSet(true);
    return this;
  }

  public void unsetIsPublic() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISPUBLIC_ISSET_ID);
  }

  /** Returns true if field isPublic is set (has been assigned a value) and false otherwise */
  public boolean isSetIsPublic() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISPUBLIC_ISSET_ID);
  }

  public void setIsPublicIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISPUBLIC_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getVisibleUsers() {
    return this.visibleUsers;
  }

  public DataPermission setVisibleUsers(@org.apache.thrift.annotation.Nullable java.lang.String visibleUsers) {
    this.visibleUsers = visibleUsers;
    return this;
  }

  public void unsetVisibleUsers() {
    this.visibleUsers = null;
  }

  /** Returns true if field visibleUsers is set (has been assigned a value) and false otherwise */
  public boolean isSetVisibleUsers() {
    return this.visibleUsers != null;
  }

  public void setVisibleUsersIsSet(boolean value) {
    if (!value) {
      this.visibleUsers = null;
    }
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public DataPermission setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case OWNER:
      if (value == null) {
        unsetOwner();
      } else {
        setOwner((java.lang.String)value);
      }
      break;

    case TABLE_PREFIX:
      if (value == null) {
        unsetTablePrefix();
      } else {
        setTablePrefix((java.lang.String)value);
      }
      break;

    case TIMESTAMP_SET:
      if (value == null) {
        unsetTimestampSet();
      } else {
        setTimestampSet((java.lang.String)value);
      }
      break;

    case IS_PUBLIC:
      if (value == null) {
        unsetIsPublic();
      } else {
        setIsPublic((java.lang.Boolean)value);
      }
      break;

    case VISIBLE_USERS:
      if (value == null) {
        unsetVisibleUsers();
      } else {
        setVisibleUsers((java.lang.String)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case OWNER:
      return getOwner();

    case TABLE_PREFIX:
      return getTablePrefix();

    case TIMESTAMP_SET:
      return getTimestampSet();

    case IS_PUBLIC:
      return isIsPublic();

    case VISIBLE_USERS:
      return getVisibleUsers();

    case CREATE_TIME:
      return getCreateTime();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case OWNER:
      return isSetOwner();
    case TABLE_PREFIX:
      return isSetTablePrefix();
    case TIMESTAMP_SET:
      return isSetTimestampSet();
    case IS_PUBLIC:
      return isSetIsPublic();
    case VISIBLE_USERS:
      return isSetVisibleUsers();
    case CREATE_TIME:
      return isSetCreateTime();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof DataPermission)
      return this.equals((DataPermission)that);
    return false;
  }

  public boolean equals(DataPermission that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_owner = true && this.isSetOwner();
    boolean that_present_owner = true && that.isSetOwner();
    if (this_present_owner || that_present_owner) {
      if (!(this_present_owner && that_present_owner))
        return false;
      if (!this.owner.equals(that.owner))
        return false;
    }

    boolean this_present_tablePrefix = true && this.isSetTablePrefix();
    boolean that_present_tablePrefix = true && that.isSetTablePrefix();
    if (this_present_tablePrefix || that_present_tablePrefix) {
      if (!(this_present_tablePrefix && that_present_tablePrefix))
        return false;
      if (!this.tablePrefix.equals(that.tablePrefix))
        return false;
    }

    boolean this_present_timestampSet = true && this.isSetTimestampSet();
    boolean that_present_timestampSet = true && that.isSetTimestampSet();
    if (this_present_timestampSet || that_present_timestampSet) {
      if (!(this_present_timestampSet && that_present_timestampSet))
        return false;
      if (!this.timestampSet.equals(that.timestampSet))
        return false;
    }

    boolean this_present_isPublic = true;
    boolean that_present_isPublic = true;
    if (this_present_isPublic || that_present_isPublic) {
      if (!(this_present_isPublic && that_present_isPublic))
        return false;
      if (this.isPublic != that.isPublic)
        return false;
    }

    boolean this_present_visibleUsers = true && this.isSetVisibleUsers();
    boolean that_present_visibleUsers = true && that.isSetVisibleUsers();
    if (this_present_visibleUsers || that_present_visibleUsers) {
      if (!(this_present_visibleUsers && that_present_visibleUsers))
        return false;
      if (!this.visibleUsers.equals(that.visibleUsers))
        return false;
    }

    boolean this_present_createTime = true && this.isSetCreateTime();
    boolean that_present_createTime = true && that.isSetCreateTime();
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(id);

    hashCode = hashCode * 8191 + ((isSetOwner()) ? 131071 : 524287);
    if (isSetOwner())
      hashCode = hashCode * 8191 + owner.hashCode();

    hashCode = hashCode * 8191 + ((isSetTablePrefix()) ? 131071 : 524287);
    if (isSetTablePrefix())
      hashCode = hashCode * 8191 + tablePrefix.hashCode();

    hashCode = hashCode * 8191 + ((isSetTimestampSet()) ? 131071 : 524287);
    if (isSetTimestampSet())
      hashCode = hashCode * 8191 + timestampSet.hashCode();

    hashCode = hashCode * 8191 + ((isPublic) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetVisibleUsers()) ? 131071 : 524287);
    if (isSetVisibleUsers())
      hashCode = hashCode * 8191 + visibleUsers.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreateTime()) ? 131071 : 524287);
    if (isSetCreateTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createTime);

    return hashCode;
  }

  @Override
  public int compareTo(DataPermission other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetId(), other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOwner(), other.isSetOwner());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwner()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.owner, other.owner);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTablePrefix(), other.isSetTablePrefix());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTablePrefix()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tablePrefix, other.tablePrefix);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTimestampSet(), other.isSetTimestampSet());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestampSet()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestampSet, other.timestampSet);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIsPublic(), other.isSetIsPublic());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsPublic()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isPublic, other.isPublic);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVisibleUsers(), other.isSetVisibleUsers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVisibleUsers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.visibleUsers, other.visibleUsers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreateTime(), other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DataPermission(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (isSetOwner()) {
      if (!first) sb.append(", ");
      sb.append("owner:");
      if (this.owner == null) {
        sb.append("null");
      } else {
        sb.append(this.owner);
      }
      first = false;
    }
    if (isSetTablePrefix()) {
      if (!first) sb.append(", ");
      sb.append("tablePrefix:");
      if (this.tablePrefix == null) {
        sb.append("null");
      } else {
        sb.append(this.tablePrefix);
      }
      first = false;
    }
    if (isSetTimestampSet()) {
      if (!first) sb.append(", ");
      sb.append("timestampSet:");
      if (this.timestampSet == null) {
        sb.append("null");
      } else {
        sb.append(this.timestampSet);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("isPublic:");
    sb.append(this.isPublic);
    first = false;
    if (isSetVisibleUsers()) {
      if (!first) sb.append(", ");
      sb.append("visibleUsers:");
      if (this.visibleUsers == null) {
        sb.append("null");
      } else {
        sb.append(this.visibleUsers);
      }
      first = false;
    }
    if (isSetCreateTime()) {
      if (!first) sb.append(", ");
      sb.append("createTime:");
      sb.append(this.createTime);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DataPermissionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DataPermissionStandardScheme getScheme() {
      return new DataPermissionStandardScheme();
    }
  }

  private static class DataPermissionStandardScheme extends org.apache.thrift.scheme.StandardScheme<DataPermission> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, DataPermission struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OWNER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.owner = iprot.readString();
              struct.setOwnerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TABLE_PREFIX
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.tablePrefix = iprot.readString();
              struct.setTablePrefixIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TIMESTAMP_SET
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.timestampSet = iprot.readString();
              struct.setTimestampSetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // IS_PUBLIC
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isPublic = iprot.readBool();
              struct.setIsPublicIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // VISIBLE_USERS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.visibleUsers = iprot.readString();
              struct.setVisibleUsersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, DataPermission struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.owner != null) {
        if (struct.isSetOwner()) {
          oprot.writeFieldBegin(OWNER_FIELD_DESC);
          oprot.writeString(struct.owner);
          oprot.writeFieldEnd();
        }
      }
      if (struct.tablePrefix != null) {
        if (struct.isSetTablePrefix()) {
          oprot.writeFieldBegin(TABLE_PREFIX_FIELD_DESC);
          oprot.writeString(struct.tablePrefix);
          oprot.writeFieldEnd();
        }
      }
      if (struct.timestampSet != null) {
        if (struct.isSetTimestampSet()) {
          oprot.writeFieldBegin(TIMESTAMP_SET_FIELD_DESC);
          oprot.writeString(struct.timestampSet);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldBegin(IS_PUBLIC_FIELD_DESC);
      oprot.writeBool(struct.isPublic);
      oprot.writeFieldEnd();
      if (struct.visibleUsers != null) {
        if (struct.isSetVisibleUsers()) {
          oprot.writeFieldBegin(VISIBLE_USERS_FIELD_DESC);
          oprot.writeString(struct.visibleUsers);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetCreateTime()) {
        oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
        oprot.writeI64(struct.createTime);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DataPermissionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DataPermissionTupleScheme getScheme() {
      return new DataPermissionTupleScheme();
    }
  }

  private static class DataPermissionTupleScheme extends org.apache.thrift.scheme.TupleScheme<DataPermission> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DataPermission struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetOwner()) {
        optionals.set(1);
      }
      if (struct.isSetTablePrefix()) {
        optionals.set(2);
      }
      if (struct.isSetTimestampSet()) {
        optionals.set(3);
      }
      if (struct.isSetIsPublic()) {
        optionals.set(4);
      }
      if (struct.isSetVisibleUsers()) {
        optionals.set(5);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(6);
      }
      oprot.writeBitSet(optionals, 7);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetOwner()) {
        oprot.writeString(struct.owner);
      }
      if (struct.isSetTablePrefix()) {
        oprot.writeString(struct.tablePrefix);
      }
      if (struct.isSetTimestampSet()) {
        oprot.writeString(struct.timestampSet);
      }
      if (struct.isSetIsPublic()) {
        oprot.writeBool(struct.isPublic);
      }
      if (struct.isSetVisibleUsers()) {
        oprot.writeString(struct.visibleUsers);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeI64(struct.createTime);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DataPermission struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(7);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.owner = iprot.readString();
        struct.setOwnerIsSet(true);
      }
      if (incoming.get(2)) {
        struct.tablePrefix = iprot.readString();
        struct.setTablePrefixIsSet(true);
      }
      if (incoming.get(3)) {
        struct.timestampSet = iprot.readString();
        struct.setTimestampSetIsSet(true);
      }
      if (incoming.get(4)) {
        struct.isPublic = iprot.readBool();
        struct.setIsPublicIsSet(true);
      }
      if (incoming.get(5)) {
        struct.visibleUsers = iprot.readString();
        struct.setVisibleUsersIsSet(true);
      }
      if (incoming.get(6)) {
        struct.createTime = iprot.readI64();
        struct.setCreateTimeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

