/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tsinghua.thrift.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-06-23")
public class SimulationArchive implements org.apache.thrift.TBase<SimulationArchive, SimulationArchive._Fields>, java.io.Serializable, Cloneable, Comparable<SimulationArchive> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SimulationArchive");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DESCRIPTION_FIELD_DESC = new org.apache.thrift.protocol.TField("description", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField GRAPH_JSON_FIELD_DESC = new org.apache.thrift.protocol.TField("graphJson", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField UPDATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("updateTime", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField OWNER_FIELD_DESC = new org.apache.thrift.protocol.TField("owner", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField PROJECT_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("projectName", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField SCHEDULE_CRON_FIELD_DESC = new org.apache.thrift.protocol.TField("scheduleCron", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField OUTPUT_API_CONFIG_FIELD_DESC = new org.apache.thrift.protocol.TField("outputApiConfig", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField LAST_EXECUTION_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("lastExecutionTime", org.apache.thrift.protocol.TType.I64, (short)11);
  private static final org.apache.thrift.protocol.TField EXECUTION_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("executionCount", org.apache.thrift.protocol.TType.I64, (short)12);
  private static final org.apache.thrift.protocol.TField IS_RUNNING_FIELD_DESC = new org.apache.thrift.protocol.TField("isRunning", org.apache.thrift.protocol.TType.BOOL, (short)13);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SimulationArchiveStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SimulationArchiveTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String name; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String description; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String graphJson; // optional
  public boolean status; // optional
  public long createTime; // optional
  public long updateTime; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String owner; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String projectName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String scheduleCron; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String outputApiConfig; // optional
  public long lastExecutionTime; // optional
  public long executionCount; // optional
  public boolean isRunning; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    DESCRIPTION((short)2, "description"),
    GRAPH_JSON((short)3, "graphJson"),
    STATUS((short)4, "status"),
    CREATE_TIME((short)5, "createTime"),
    UPDATE_TIME((short)6, "updateTime"),
    OWNER((short)7, "owner"),
    PROJECT_NAME((short)8, "projectName"),
    SCHEDULE_CRON((short)9, "scheduleCron"),
    OUTPUT_API_CONFIG((short)10, "outputApiConfig"),
    LAST_EXECUTION_TIME((short)11, "lastExecutionTime"),
    EXECUTION_COUNT((short)12, "executionCount"),
    IS_RUNNING((short)13, "isRunning");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // DESCRIPTION
          return DESCRIPTION;
        case 3: // GRAPH_JSON
          return GRAPH_JSON;
        case 4: // STATUS
          return STATUS;
        case 5: // CREATE_TIME
          return CREATE_TIME;
        case 6: // UPDATE_TIME
          return UPDATE_TIME;
        case 7: // OWNER
          return OWNER;
        case 8: // PROJECT_NAME
          return PROJECT_NAME;
        case 9: // SCHEDULE_CRON
          return SCHEDULE_CRON;
        case 10: // OUTPUT_API_CONFIG
          return OUTPUT_API_CONFIG;
        case 11: // LAST_EXECUTION_TIME
          return LAST_EXECUTION_TIME;
        case 12: // EXECUTION_COUNT
          return EXECUTION_COUNT;
        case 13: // IS_RUNNING
          return IS_RUNNING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __STATUS_ISSET_ID = 0;
  private static final int __CREATETIME_ISSET_ID = 1;
  private static final int __UPDATETIME_ISSET_ID = 2;
  private static final int __LASTEXECUTIONTIME_ISSET_ID = 3;
  private static final int __EXECUTIONCOUNT_ISSET_ID = 4;
  private static final int __ISRUNNING_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.DESCRIPTION,_Fields.GRAPH_JSON,_Fields.STATUS,_Fields.CREATE_TIME,_Fields.UPDATE_TIME,_Fields.OWNER,_Fields.PROJECT_NAME,_Fields.SCHEDULE_CRON,_Fields.OUTPUT_API_CONFIG,_Fields.LAST_EXECUTION_TIME,_Fields.EXECUTION_COUNT,_Fields.IS_RUNNING};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DESCRIPTION, new org.apache.thrift.meta_data.FieldMetaData("description", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.GRAPH_JSON, new org.apache.thrift.meta_data.FieldMetaData("graphJson", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.UPDATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("updateTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.OWNER, new org.apache.thrift.meta_data.FieldMetaData("owner", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROJECT_NAME, new org.apache.thrift.meta_data.FieldMetaData("projectName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SCHEDULE_CRON, new org.apache.thrift.meta_data.FieldMetaData("scheduleCron", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OUTPUT_API_CONFIG, new org.apache.thrift.meta_data.FieldMetaData("outputApiConfig", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LAST_EXECUTION_TIME, new org.apache.thrift.meta_data.FieldMetaData("lastExecutionTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.EXECUTION_COUNT, new org.apache.thrift.meta_data.FieldMetaData("executionCount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.IS_RUNNING, new org.apache.thrift.meta_data.FieldMetaData("isRunning", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SimulationArchive.class, metaDataMap);
  }

  public SimulationArchive() {
  }

  public SimulationArchive(
    java.lang.String name)
  {
    this();
    this.name = name;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SimulationArchive(SimulationArchive other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetDescription()) {
      this.description = other.description;
    }
    if (other.isSetGraphJson()) {
      this.graphJson = other.graphJson;
    }
    this.status = other.status;
    this.createTime = other.createTime;
    this.updateTime = other.updateTime;
    if (other.isSetOwner()) {
      this.owner = other.owner;
    }
    if (other.isSetProjectName()) {
      this.projectName = other.projectName;
    }
    if (other.isSetScheduleCron()) {
      this.scheduleCron = other.scheduleCron;
    }
    if (other.isSetOutputApiConfig()) {
      this.outputApiConfig = other.outputApiConfig;
    }
    this.lastExecutionTime = other.lastExecutionTime;
    this.executionCount = other.executionCount;
    this.isRunning = other.isRunning;
  }

  @Override
  public SimulationArchive deepCopy() {
    return new SimulationArchive(this);
  }

  @Override
  public void clear() {
    this.name = null;
    this.description = null;
    this.graphJson = null;
    setStatusIsSet(false);
    this.status = false;
    setCreateTimeIsSet(false);
    this.createTime = 0;
    setUpdateTimeIsSet(false);
    this.updateTime = 0;
    this.owner = null;
    this.projectName = null;
    this.scheduleCron = null;
    this.outputApiConfig = null;
    setLastExecutionTimeIsSet(false);
    this.lastExecutionTime = 0;
    setExecutionCountIsSet(false);
    this.executionCount = 0;
    setIsRunningIsSet(false);
    this.isRunning = false;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getName() {
    return this.name;
  }

  public SimulationArchive setName(@org.apache.thrift.annotation.Nullable java.lang.String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDescription() {
    return this.description;
  }

  public SimulationArchive setDescription(@org.apache.thrift.annotation.Nullable java.lang.String description) {
    this.description = description;
    return this;
  }

  public void unsetDescription() {
    this.description = null;
  }

  /** Returns true if field description is set (has been assigned a value) and false otherwise */
  public boolean isSetDescription() {
    return this.description != null;
  }

  public void setDescriptionIsSet(boolean value) {
    if (!value) {
      this.description = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getGraphJson() {
    return this.graphJson;
  }

  public SimulationArchive setGraphJson(@org.apache.thrift.annotation.Nullable java.lang.String graphJson) {
    this.graphJson = graphJson;
    return this;
  }

  public void unsetGraphJson() {
    this.graphJson = null;
  }

  /** Returns true if field graphJson is set (has been assigned a value) and false otherwise */
  public boolean isSetGraphJson() {
    return this.graphJson != null;
  }

  public void setGraphJsonIsSet(boolean value) {
    if (!value) {
      this.graphJson = null;
    }
  }

  public boolean isStatus() {
    return this.status;
  }

  public SimulationArchive setStatus(boolean status) {
    this.status = status;
    setStatusIsSet(true);
    return this;
  }

  public void unsetStatus() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STATUS_ISSET_ID);
  }

  public void setStatusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STATUS_ISSET_ID, value);
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public SimulationArchive setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  public long getUpdateTime() {
    return this.updateTime;
  }

  public SimulationArchive setUpdateTime(long updateTime) {
    this.updateTime = updateTime;
    setUpdateTimeIsSet(true);
    return this;
  }

  public void unsetUpdateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UPDATETIME_ISSET_ID);
  }

  /** Returns true if field updateTime is set (has been assigned a value) and false otherwise */
  public boolean isSetUpdateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UPDATETIME_ISSET_ID);
  }

  public void setUpdateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UPDATETIME_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOwner() {
    return this.owner;
  }

  public SimulationArchive setOwner(@org.apache.thrift.annotation.Nullable java.lang.String owner) {
    this.owner = owner;
    return this;
  }

  public void unsetOwner() {
    this.owner = null;
  }

  /** Returns true if field owner is set (has been assigned a value) and false otherwise */
  public boolean isSetOwner() {
    return this.owner != null;
  }

  public void setOwnerIsSet(boolean value) {
    if (!value) {
      this.owner = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getProjectName() {
    return this.projectName;
  }

  public SimulationArchive setProjectName(@org.apache.thrift.annotation.Nullable java.lang.String projectName) {
    this.projectName = projectName;
    return this;
  }

  public void unsetProjectName() {
    this.projectName = null;
  }

  /** Returns true if field projectName is set (has been assigned a value) and false otherwise */
  public boolean isSetProjectName() {
    return this.projectName != null;
  }

  public void setProjectNameIsSet(boolean value) {
    if (!value) {
      this.projectName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getScheduleCron() {
    return this.scheduleCron;
  }

  public SimulationArchive setScheduleCron(@org.apache.thrift.annotation.Nullable java.lang.String scheduleCron) {
    this.scheduleCron = scheduleCron;
    return this;
  }

  public void unsetScheduleCron() {
    this.scheduleCron = null;
  }

  /** Returns true if field scheduleCron is set (has been assigned a value) and false otherwise */
  public boolean isSetScheduleCron() {
    return this.scheduleCron != null;
  }

  public void setScheduleCronIsSet(boolean value) {
    if (!value) {
      this.scheduleCron = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOutputApiConfig() {
    return this.outputApiConfig;
  }

  public SimulationArchive setOutputApiConfig(@org.apache.thrift.annotation.Nullable java.lang.String outputApiConfig) {
    this.outputApiConfig = outputApiConfig;
    return this;
  }

  public void unsetOutputApiConfig() {
    this.outputApiConfig = null;
  }

  /** Returns true if field outputApiConfig is set (has been assigned a value) and false otherwise */
  public boolean isSetOutputApiConfig() {
    return this.outputApiConfig != null;
  }

  public void setOutputApiConfigIsSet(boolean value) {
    if (!value) {
      this.outputApiConfig = null;
    }
  }

  public long getLastExecutionTime() {
    return this.lastExecutionTime;
  }

  public SimulationArchive setLastExecutionTime(long lastExecutionTime) {
    this.lastExecutionTime = lastExecutionTime;
    setLastExecutionTimeIsSet(true);
    return this;
  }

  public void unsetLastExecutionTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LASTEXECUTIONTIME_ISSET_ID);
  }

  /** Returns true if field lastExecutionTime is set (has been assigned a value) and false otherwise */
  public boolean isSetLastExecutionTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LASTEXECUTIONTIME_ISSET_ID);
  }

  public void setLastExecutionTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LASTEXECUTIONTIME_ISSET_ID, value);
  }

  public long getExecutionCount() {
    return this.executionCount;
  }

  public SimulationArchive setExecutionCount(long executionCount) {
    this.executionCount = executionCount;
    setExecutionCountIsSet(true);
    return this;
  }

  public void unsetExecutionCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EXECUTIONCOUNT_ISSET_ID);
  }

  /** Returns true if field executionCount is set (has been assigned a value) and false otherwise */
  public boolean isSetExecutionCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EXECUTIONCOUNT_ISSET_ID);
  }

  public void setExecutionCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EXECUTIONCOUNT_ISSET_ID, value);
  }

  public boolean isIsRunning() {
    return this.isRunning;
  }

  public SimulationArchive setIsRunning(boolean isRunning) {
    this.isRunning = isRunning;
    setIsRunningIsSet(true);
    return this;
  }

  public void unsetIsRunning() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ISRUNNING_ISSET_ID);
  }

  /** Returns true if field isRunning is set (has been assigned a value) and false otherwise */
  public boolean isSetIsRunning() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ISRUNNING_ISSET_ID);
  }

  public void setIsRunningIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ISRUNNING_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case DESCRIPTION:
      if (value == null) {
        unsetDescription();
      } else {
        setDescription((java.lang.String)value);
      }
      break;

    case GRAPH_JSON:
      if (value == null) {
        unsetGraphJson();
      } else {
        setGraphJson((java.lang.String)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((java.lang.Boolean)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((java.lang.Long)value);
      }
      break;

    case UPDATE_TIME:
      if (value == null) {
        unsetUpdateTime();
      } else {
        setUpdateTime((java.lang.Long)value);
      }
      break;

    case OWNER:
      if (value == null) {
        unsetOwner();
      } else {
        setOwner((java.lang.String)value);
      }
      break;

    case PROJECT_NAME:
      if (value == null) {
        unsetProjectName();
      } else {
        setProjectName((java.lang.String)value);
      }
      break;

    case SCHEDULE_CRON:
      if (value == null) {
        unsetScheduleCron();
      } else {
        setScheduleCron((java.lang.String)value);
      }
      break;

    case OUTPUT_API_CONFIG:
      if (value == null) {
        unsetOutputApiConfig();
      } else {
        setOutputApiConfig((java.lang.String)value);
      }
      break;

    case LAST_EXECUTION_TIME:
      if (value == null) {
        unsetLastExecutionTime();
      } else {
        setLastExecutionTime((java.lang.Long)value);
      }
      break;

    case EXECUTION_COUNT:
      if (value == null) {
        unsetExecutionCount();
      } else {
        setExecutionCount((java.lang.Long)value);
      }
      break;

    case IS_RUNNING:
      if (value == null) {
        unsetIsRunning();
      } else {
        setIsRunning((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case DESCRIPTION:
      return getDescription();

    case GRAPH_JSON:
      return getGraphJson();

    case STATUS:
      return isStatus();

    case CREATE_TIME:
      return getCreateTime();

    case UPDATE_TIME:
      return getUpdateTime();

    case OWNER:
      return getOwner();

    case PROJECT_NAME:
      return getProjectName();

    case SCHEDULE_CRON:
      return getScheduleCron();

    case OUTPUT_API_CONFIG:
      return getOutputApiConfig();

    case LAST_EXECUTION_TIME:
      return getLastExecutionTime();

    case EXECUTION_COUNT:
      return getExecutionCount();

    case IS_RUNNING:
      return isIsRunning();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case DESCRIPTION:
      return isSetDescription();
    case GRAPH_JSON:
      return isSetGraphJson();
    case STATUS:
      return isSetStatus();
    case CREATE_TIME:
      return isSetCreateTime();
    case UPDATE_TIME:
      return isSetUpdateTime();
    case OWNER:
      return isSetOwner();
    case PROJECT_NAME:
      return isSetProjectName();
    case SCHEDULE_CRON:
      return isSetScheduleCron();
    case OUTPUT_API_CONFIG:
      return isSetOutputApiConfig();
    case LAST_EXECUTION_TIME:
      return isSetLastExecutionTime();
    case EXECUTION_COUNT:
      return isSetExecutionCount();
    case IS_RUNNING:
      return isSetIsRunning();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof SimulationArchive)
      return this.equals((SimulationArchive)that);
    return false;
  }

  public boolean equals(SimulationArchive that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_description = true && this.isSetDescription();
    boolean that_present_description = true && that.isSetDescription();
    if (this_present_description || that_present_description) {
      if (!(this_present_description && that_present_description))
        return false;
      if (!this.description.equals(that.description))
        return false;
    }

    boolean this_present_graphJson = true && this.isSetGraphJson();
    boolean that_present_graphJson = true && that.isSetGraphJson();
    if (this_present_graphJson || that_present_graphJson) {
      if (!(this_present_graphJson && that_present_graphJson))
        return false;
      if (!this.graphJson.equals(that.graphJson))
        return false;
    }

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (this.status != that.status)
        return false;
    }

    boolean this_present_createTime = true && this.isSetCreateTime();
    boolean that_present_createTime = true && that.isSetCreateTime();
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    boolean this_present_updateTime = true && this.isSetUpdateTime();
    boolean that_present_updateTime = true && that.isSetUpdateTime();
    if (this_present_updateTime || that_present_updateTime) {
      if (!(this_present_updateTime && that_present_updateTime))
        return false;
      if (this.updateTime != that.updateTime)
        return false;
    }

    boolean this_present_owner = true && this.isSetOwner();
    boolean that_present_owner = true && that.isSetOwner();
    if (this_present_owner || that_present_owner) {
      if (!(this_present_owner && that_present_owner))
        return false;
      if (!this.owner.equals(that.owner))
        return false;
    }

    boolean this_present_projectName = true && this.isSetProjectName();
    boolean that_present_projectName = true && that.isSetProjectName();
    if (this_present_projectName || that_present_projectName) {
      if (!(this_present_projectName && that_present_projectName))
        return false;
      if (!this.projectName.equals(that.projectName))
        return false;
    }

    boolean this_present_scheduleCron = true && this.isSetScheduleCron();
    boolean that_present_scheduleCron = true && that.isSetScheduleCron();
    if (this_present_scheduleCron || that_present_scheduleCron) {
      if (!(this_present_scheduleCron && that_present_scheduleCron))
        return false;
      if (!this.scheduleCron.equals(that.scheduleCron))
        return false;
    }

    boolean this_present_outputApiConfig = true && this.isSetOutputApiConfig();
    boolean that_present_outputApiConfig = true && that.isSetOutputApiConfig();
    if (this_present_outputApiConfig || that_present_outputApiConfig) {
      if (!(this_present_outputApiConfig && that_present_outputApiConfig))
        return false;
      if (!this.outputApiConfig.equals(that.outputApiConfig))
        return false;
    }

    boolean this_present_lastExecutionTime = true && this.isSetLastExecutionTime();
    boolean that_present_lastExecutionTime = true && that.isSetLastExecutionTime();
    if (this_present_lastExecutionTime || that_present_lastExecutionTime) {
      if (!(this_present_lastExecutionTime && that_present_lastExecutionTime))
        return false;
      if (this.lastExecutionTime != that.lastExecutionTime)
        return false;
    }

    boolean this_present_executionCount = true && this.isSetExecutionCount();
    boolean that_present_executionCount = true && that.isSetExecutionCount();
    if (this_present_executionCount || that_present_executionCount) {
      if (!(this_present_executionCount && that_present_executionCount))
        return false;
      if (this.executionCount != that.executionCount)
        return false;
    }

    boolean this_present_isRunning = true && this.isSetIsRunning();
    boolean that_present_isRunning = true && that.isSetIsRunning();
    if (this_present_isRunning || that_present_isRunning) {
      if (!(this_present_isRunning && that_present_isRunning))
        return false;
      if (this.isRunning != that.isRunning)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((isSetDescription()) ? 131071 : 524287);
    if (isSetDescription())
      hashCode = hashCode * 8191 + description.hashCode();

    hashCode = hashCode * 8191 + ((isSetGraphJson()) ? 131071 : 524287);
    if (isSetGraphJson())
      hashCode = hashCode * 8191 + graphJson.hashCode();

    hashCode = hashCode * 8191 + ((isSetStatus()) ? 131071 : 524287);
    if (isSetStatus())
      hashCode = hashCode * 8191 + ((status) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetCreateTime()) ? 131071 : 524287);
    if (isSetCreateTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createTime);

    hashCode = hashCode * 8191 + ((isSetUpdateTime()) ? 131071 : 524287);
    if (isSetUpdateTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(updateTime);

    hashCode = hashCode * 8191 + ((isSetOwner()) ? 131071 : 524287);
    if (isSetOwner())
      hashCode = hashCode * 8191 + owner.hashCode();

    hashCode = hashCode * 8191 + ((isSetProjectName()) ? 131071 : 524287);
    if (isSetProjectName())
      hashCode = hashCode * 8191 + projectName.hashCode();

    hashCode = hashCode * 8191 + ((isSetScheduleCron()) ? 131071 : 524287);
    if (isSetScheduleCron())
      hashCode = hashCode * 8191 + scheduleCron.hashCode();

    hashCode = hashCode * 8191 + ((isSetOutputApiConfig()) ? 131071 : 524287);
    if (isSetOutputApiConfig())
      hashCode = hashCode * 8191 + outputApiConfig.hashCode();

    hashCode = hashCode * 8191 + ((isSetLastExecutionTime()) ? 131071 : 524287);
    if (isSetLastExecutionTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(lastExecutionTime);

    hashCode = hashCode * 8191 + ((isSetExecutionCount()) ? 131071 : 524287);
    if (isSetExecutionCount())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(executionCount);

    hashCode = hashCode * 8191 + ((isSetIsRunning()) ? 131071 : 524287);
    if (isSetIsRunning())
      hashCode = hashCode * 8191 + ((isRunning) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(SimulationArchive other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetName(), other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDescription(), other.isSetDescription());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDescription()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.description, other.description);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetGraphJson(), other.isSetGraphJson());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGraphJson()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.graphJson, other.graphJson);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStatus(), other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreateTime(), other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUpdateTime(), other.isSetUpdateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUpdateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.updateTime, other.updateTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOwner(), other.isSetOwner());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwner()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.owner, other.owner);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetProjectName(), other.isSetProjectName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProjectName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.projectName, other.projectName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetScheduleCron(), other.isSetScheduleCron());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScheduleCron()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scheduleCron, other.scheduleCron);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOutputApiConfig(), other.isSetOutputApiConfig());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutputApiConfig()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outputApiConfig, other.outputApiConfig);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLastExecutionTime(), other.isSetLastExecutionTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastExecutionTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastExecutionTime, other.lastExecutionTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetExecutionCount(), other.isSetExecutionCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExecutionCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.executionCount, other.executionCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIsRunning(), other.isSetIsRunning());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsRunning()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isRunning, other.isRunning);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SimulationArchive(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (isSetDescription()) {
      if (!first) sb.append(", ");
      sb.append("description:");
      if (this.description == null) {
        sb.append("null");
      } else {
        sb.append(this.description);
      }
      first = false;
    }
    if (isSetGraphJson()) {
      if (!first) sb.append(", ");
      sb.append("graphJson:");
      if (this.graphJson == null) {
        sb.append("null");
      } else {
        sb.append(this.graphJson);
      }
      first = false;
    }
    if (isSetStatus()) {
      if (!first) sb.append(", ");
      sb.append("status:");
      sb.append(this.status);
      first = false;
    }
    if (isSetCreateTime()) {
      if (!first) sb.append(", ");
      sb.append("createTime:");
      sb.append(this.createTime);
      first = false;
    }
    if (isSetUpdateTime()) {
      if (!first) sb.append(", ");
      sb.append("updateTime:");
      sb.append(this.updateTime);
      first = false;
    }
    if (isSetOwner()) {
      if (!first) sb.append(", ");
      sb.append("owner:");
      if (this.owner == null) {
        sb.append("null");
      } else {
        sb.append(this.owner);
      }
      first = false;
    }
    if (isSetProjectName()) {
      if (!first) sb.append(", ");
      sb.append("projectName:");
      if (this.projectName == null) {
        sb.append("null");
      } else {
        sb.append(this.projectName);
      }
      first = false;
    }
    if (isSetScheduleCron()) {
      if (!first) sb.append(", ");
      sb.append("scheduleCron:");
      if (this.scheduleCron == null) {
        sb.append("null");
      } else {
        sb.append(this.scheduleCron);
      }
      first = false;
    }
    if (isSetOutputApiConfig()) {
      if (!first) sb.append(", ");
      sb.append("outputApiConfig:");
      if (this.outputApiConfig == null) {
        sb.append("null");
      } else {
        sb.append(this.outputApiConfig);
      }
      first = false;
    }
    if (isSetLastExecutionTime()) {
      if (!first) sb.append(", ");
      sb.append("lastExecutionTime:");
      sb.append(this.lastExecutionTime);
      first = false;
    }
    if (isSetExecutionCount()) {
      if (!first) sb.append(", ");
      sb.append("executionCount:");
      sb.append(this.executionCount);
      first = false;
    }
    if (isSetIsRunning()) {
      if (!first) sb.append(", ");
      sb.append("isRunning:");
      sb.append(this.isRunning);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SimulationArchiveStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SimulationArchiveStandardScheme getScheme() {
      return new SimulationArchiveStandardScheme();
    }
  }

  private static class SimulationArchiveStandardScheme extends org.apache.thrift.scheme.StandardScheme<SimulationArchive> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, SimulationArchive struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DESCRIPTION
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.description = iprot.readString();
              struct.setDescriptionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // GRAPH_JSON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.graphJson = iprot.readString();
              struct.setGraphJsonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.status = iprot.readBool();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // UPDATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.updateTime = iprot.readI64();
              struct.setUpdateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // OWNER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.owner = iprot.readString();
              struct.setOwnerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // PROJECT_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.projectName = iprot.readString();
              struct.setProjectNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // SCHEDULE_CRON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.scheduleCron = iprot.readString();
              struct.setScheduleCronIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // OUTPUT_API_CONFIG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.outputApiConfig = iprot.readString();
              struct.setOutputApiConfigIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // LAST_EXECUTION_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.lastExecutionTime = iprot.readI64();
              struct.setLastExecutionTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // EXECUTION_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.executionCount = iprot.readI64();
              struct.setExecutionCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // IS_RUNNING
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isRunning = iprot.readBool();
              struct.setIsRunningIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, SimulationArchive struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.description != null) {
        if (struct.isSetDescription()) {
          oprot.writeFieldBegin(DESCRIPTION_FIELD_DESC);
          oprot.writeString(struct.description);
          oprot.writeFieldEnd();
        }
      }
      if (struct.graphJson != null) {
        if (struct.isSetGraphJson()) {
          oprot.writeFieldBegin(GRAPH_JSON_FIELD_DESC);
          oprot.writeString(struct.graphJson);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetStatus()) {
        oprot.writeFieldBegin(STATUS_FIELD_DESC);
        oprot.writeBool(struct.status);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCreateTime()) {
        oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
        oprot.writeI64(struct.createTime);
        oprot.writeFieldEnd();
      }
      if (struct.isSetUpdateTime()) {
        oprot.writeFieldBegin(UPDATE_TIME_FIELD_DESC);
        oprot.writeI64(struct.updateTime);
        oprot.writeFieldEnd();
      }
      if (struct.owner != null) {
        if (struct.isSetOwner()) {
          oprot.writeFieldBegin(OWNER_FIELD_DESC);
          oprot.writeString(struct.owner);
          oprot.writeFieldEnd();
        }
      }
      if (struct.projectName != null) {
        if (struct.isSetProjectName()) {
          oprot.writeFieldBegin(PROJECT_NAME_FIELD_DESC);
          oprot.writeString(struct.projectName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.scheduleCron != null) {
        if (struct.isSetScheduleCron()) {
          oprot.writeFieldBegin(SCHEDULE_CRON_FIELD_DESC);
          oprot.writeString(struct.scheduleCron);
          oprot.writeFieldEnd();
        }
      }
      if (struct.outputApiConfig != null) {
        if (struct.isSetOutputApiConfig()) {
          oprot.writeFieldBegin(OUTPUT_API_CONFIG_FIELD_DESC);
          oprot.writeString(struct.outputApiConfig);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetLastExecutionTime()) {
        oprot.writeFieldBegin(LAST_EXECUTION_TIME_FIELD_DESC);
        oprot.writeI64(struct.lastExecutionTime);
        oprot.writeFieldEnd();
      }
      if (struct.isSetExecutionCount()) {
        oprot.writeFieldBegin(EXECUTION_COUNT_FIELD_DESC);
        oprot.writeI64(struct.executionCount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIsRunning()) {
        oprot.writeFieldBegin(IS_RUNNING_FIELD_DESC);
        oprot.writeBool(struct.isRunning);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SimulationArchiveTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SimulationArchiveTupleScheme getScheme() {
      return new SimulationArchiveTupleScheme();
    }
  }

  private static class SimulationArchiveTupleScheme extends org.apache.thrift.scheme.TupleScheme<SimulationArchive> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SimulationArchive struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetName()) {
        optionals.set(0);
      }
      if (struct.isSetDescription()) {
        optionals.set(1);
      }
      if (struct.isSetGraphJson()) {
        optionals.set(2);
      }
      if (struct.isSetStatus()) {
        optionals.set(3);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(4);
      }
      if (struct.isSetUpdateTime()) {
        optionals.set(5);
      }
      if (struct.isSetOwner()) {
        optionals.set(6);
      }
      if (struct.isSetProjectName()) {
        optionals.set(7);
      }
      if (struct.isSetScheduleCron()) {
        optionals.set(8);
      }
      if (struct.isSetOutputApiConfig()) {
        optionals.set(9);
      }
      if (struct.isSetLastExecutionTime()) {
        optionals.set(10);
      }
      if (struct.isSetExecutionCount()) {
        optionals.set(11);
      }
      if (struct.isSetIsRunning()) {
        optionals.set(12);
      }
      oprot.writeBitSet(optionals, 13);
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetDescription()) {
        oprot.writeString(struct.description);
      }
      if (struct.isSetGraphJson()) {
        oprot.writeString(struct.graphJson);
      }
      if (struct.isSetStatus()) {
        oprot.writeBool(struct.status);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeI64(struct.createTime);
      }
      if (struct.isSetUpdateTime()) {
        oprot.writeI64(struct.updateTime);
      }
      if (struct.isSetOwner()) {
        oprot.writeString(struct.owner);
      }
      if (struct.isSetProjectName()) {
        oprot.writeString(struct.projectName);
      }
      if (struct.isSetScheduleCron()) {
        oprot.writeString(struct.scheduleCron);
      }
      if (struct.isSetOutputApiConfig()) {
        oprot.writeString(struct.outputApiConfig);
      }
      if (struct.isSetLastExecutionTime()) {
        oprot.writeI64(struct.lastExecutionTime);
      }
      if (struct.isSetExecutionCount()) {
        oprot.writeI64(struct.executionCount);
      }
      if (struct.isSetIsRunning()) {
        oprot.writeBool(struct.isRunning);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SimulationArchive struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(13);
      if (incoming.get(0)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.description = iprot.readString();
        struct.setDescriptionIsSet(true);
      }
      if (incoming.get(2)) {
        struct.graphJson = iprot.readString();
        struct.setGraphJsonIsSet(true);
      }
      if (incoming.get(3)) {
        struct.status = iprot.readBool();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(4)) {
        struct.createTime = iprot.readI64();
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.updateTime = iprot.readI64();
        struct.setUpdateTimeIsSet(true);
      }
      if (incoming.get(6)) {
        struct.owner = iprot.readString();
        struct.setOwnerIsSet(true);
      }
      if (incoming.get(7)) {
        struct.projectName = iprot.readString();
        struct.setProjectNameIsSet(true);
      }
      if (incoming.get(8)) {
        struct.scheduleCron = iprot.readString();
        struct.setScheduleCronIsSet(true);
      }
      if (incoming.get(9)) {
        struct.outputApiConfig = iprot.readString();
        struct.setOutputApiConfigIsSet(true);
      }
      if (incoming.get(10)) {
        struct.lastExecutionTime = iprot.readI64();
        struct.setLastExecutionTimeIsSet(true);
      }
      if (incoming.get(11)) {
        struct.executionCount = iprot.readI64();
        struct.setExecutionCountIsSet(true);
      }
      if (incoming.get(12)) {
        struct.isRunning = iprot.readBool();
        struct.setIsRunningIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

