/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tsinghua.thrift.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-05-29")
public class SimulationExecution implements org.apache.thrift.TBase<SimulationExecution, SimulationExecution._Fields>, java.io.Serializable, Cloneable, Comparable<SimulationExecution> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SimulationExecution");

  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timestamp", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField ARCHIVE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("archiveId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField ARCHIVE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("archiveName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField START_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("startTime", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField END_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("endTime", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField INPUT_MEASUREMENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("inputMeasurements", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField OUTPUT_MEASUREMENTS_FIELD_DESC = new org.apache.thrift.protocol.TField("outputMeasurements", org.apache.thrift.protocol.TType.STRING, (short)8);
  private static final org.apache.thrift.protocol.TField OUTPUT_TABLE_FIELD_DESC = new org.apache.thrift.protocol.TField("outputTable", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField RESULT_FIELD_DESC = new org.apache.thrift.protocol.TField("result", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.STRING, (short)11);
  private static final org.apache.thrift.protocol.TField PROCESS_LOG_FIELD_DESC = new org.apache.thrift.protocol.TField("processLog", org.apache.thrift.protocol.TType.STRING, (short)12);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SimulationExecutionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SimulationExecutionTupleSchemeFactory();

  public long timestamp; // required
  public long archiveId; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String archiveName; // optional
  public long startTime; // optional
  public long endTime; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String status; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String inputMeasurements; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String outputMeasurements; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String outputTable; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String result; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String error; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String processLog; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TIMESTAMP((short)1, "timestamp"),
    ARCHIVE_ID((short)2, "archiveId"),
    ARCHIVE_NAME((short)3, "archiveName"),
    START_TIME((short)4, "startTime"),
    END_TIME((short)5, "endTime"),
    STATUS((short)6, "status"),
    INPUT_MEASUREMENTS((short)7, "inputMeasurements"),
    OUTPUT_MEASUREMENTS((short)8, "outputMeasurements"),
    OUTPUT_TABLE((short)9, "outputTable"),
    RESULT((short)10, "result"),
    ERROR((short)11, "error"),
    PROCESS_LOG((short)12, "processLog");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TIMESTAMP
          return TIMESTAMP;
        case 2: // ARCHIVE_ID
          return ARCHIVE_ID;
        case 3: // ARCHIVE_NAME
          return ARCHIVE_NAME;
        case 4: // START_TIME
          return START_TIME;
        case 5: // END_TIME
          return END_TIME;
        case 6: // STATUS
          return STATUS;
        case 7: // INPUT_MEASUREMENTS
          return INPUT_MEASUREMENTS;
        case 8: // OUTPUT_MEASUREMENTS
          return OUTPUT_MEASUREMENTS;
        case 9: // OUTPUT_TABLE
          return OUTPUT_TABLE;
        case 10: // RESULT
          return RESULT;
        case 11: // ERROR
          return ERROR;
        case 12: // PROCESS_LOG
          return PROCESS_LOG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMESTAMP_ISSET_ID = 0;
  private static final int __ARCHIVEID_ISSET_ID = 1;
  private static final int __STARTTIME_ISSET_ID = 2;
  private static final int __ENDTIME_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.ARCHIVE_ID,_Fields.ARCHIVE_NAME,_Fields.START_TIME,_Fields.END_TIME,_Fields.STATUS,_Fields.INPUT_MEASUREMENTS,_Fields.OUTPUT_MEASUREMENTS,_Fields.OUTPUT_TABLE,_Fields.RESULT,_Fields.ERROR,_Fields.PROCESS_LOG};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("timestamp", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ARCHIVE_ID, new org.apache.thrift.meta_data.FieldMetaData("archiveId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ARCHIVE_NAME, new org.apache.thrift.meta_data.FieldMetaData("archiveName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.START_TIME, new org.apache.thrift.meta_data.FieldMetaData("startTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.END_TIME, new org.apache.thrift.meta_data.FieldMetaData("endTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INPUT_MEASUREMENTS, new org.apache.thrift.meta_data.FieldMetaData("inputMeasurements", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OUTPUT_MEASUREMENTS, new org.apache.thrift.meta_data.FieldMetaData("outputMeasurements", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OUTPUT_TABLE, new org.apache.thrift.meta_data.FieldMetaData("outputTable", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RESULT, new org.apache.thrift.meta_data.FieldMetaData("result", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ERROR, new org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROCESS_LOG, new org.apache.thrift.meta_data.FieldMetaData("processLog", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SimulationExecution.class, metaDataMap);
  }

  public SimulationExecution() {
  }

  public SimulationExecution(
    long timestamp)
  {
    this();
    this.timestamp = timestamp;
    setTimestampIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SimulationExecution(SimulationExecution other) {
    __isset_bitfield = other.__isset_bitfield;
    this.timestamp = other.timestamp;
    this.archiveId = other.archiveId;
    if (other.isSetArchiveName()) {
      this.archiveName = other.archiveName;
    }
    this.startTime = other.startTime;
    this.endTime = other.endTime;
    if (other.isSetStatus()) {
      this.status = other.status;
    }
    if (other.isSetInputMeasurements()) {
      this.inputMeasurements = other.inputMeasurements;
    }
    if (other.isSetOutputMeasurements()) {
      this.outputMeasurements = other.outputMeasurements;
    }
    if (other.isSetOutputTable()) {
      this.outputTable = other.outputTable;
    }
    if (other.isSetResult()) {
      this.result = other.result;
    }
    if (other.isSetError()) {
      this.error = other.error;
    }
    if (other.isSetProcessLog()) {
      this.processLog = other.processLog;
    }
  }

  @Override
  public SimulationExecution deepCopy() {
    return new SimulationExecution(this);
  }

  @Override
  public void clear() {
    setTimestampIsSet(false);
    this.timestamp = 0;
    setArchiveIdIsSet(false);
    this.archiveId = 0;
    this.archiveName = null;
    setStartTimeIsSet(false);
    this.startTime = 0;
    setEndTimeIsSet(false);
    this.endTime = 0;
    this.status = null;
    this.inputMeasurements = null;
    this.outputMeasurements = null;
    this.outputTable = null;
    this.result = null;
    this.error = null;
    this.processLog = null;
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public SimulationExecution setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    return this;
  }

  public void unsetTimestamp() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public long getArchiveId() {
    return this.archiveId;
  }

  public SimulationExecution setArchiveId(long archiveId) {
    this.archiveId = archiveId;
    setArchiveIdIsSet(true);
    return this;
  }

  public void unsetArchiveId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ARCHIVEID_ISSET_ID);
  }

  /** Returns true if field archiveId is set (has been assigned a value) and false otherwise */
  public boolean isSetArchiveId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ARCHIVEID_ISSET_ID);
  }

  public void setArchiveIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ARCHIVEID_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getArchiveName() {
    return this.archiveName;
  }

  public SimulationExecution setArchiveName(@org.apache.thrift.annotation.Nullable java.lang.String archiveName) {
    this.archiveName = archiveName;
    return this;
  }

  public void unsetArchiveName() {
    this.archiveName = null;
  }

  /** Returns true if field archiveName is set (has been assigned a value) and false otherwise */
  public boolean isSetArchiveName() {
    return this.archiveName != null;
  }

  public void setArchiveNameIsSet(boolean value) {
    if (!value) {
      this.archiveName = null;
    }
  }

  public long getStartTime() {
    return this.startTime;
  }

  public SimulationExecution setStartTime(long startTime) {
    this.startTime = startTime;
    setStartTimeIsSet(true);
    return this;
  }

  public void unsetStartTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STARTTIME_ISSET_ID);
  }

  /** Returns true if field startTime is set (has been assigned a value) and false otherwise */
  public boolean isSetStartTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STARTTIME_ISSET_ID);
  }

  public void setStartTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STARTTIME_ISSET_ID, value);
  }

  public long getEndTime() {
    return this.endTime;
  }

  public SimulationExecution setEndTime(long endTime) {
    this.endTime = endTime;
    setEndTimeIsSet(true);
    return this;
  }

  public void unsetEndTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENDTIME_ISSET_ID);
  }

  /** Returns true if field endTime is set (has been assigned a value) and false otherwise */
  public boolean isSetEndTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENDTIME_ISSET_ID);
  }

  public void setEndTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENDTIME_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getStatus() {
    return this.status;
  }

  public SimulationExecution setStatus(@org.apache.thrift.annotation.Nullable java.lang.String status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getInputMeasurements() {
    return this.inputMeasurements;
  }

  public SimulationExecution setInputMeasurements(@org.apache.thrift.annotation.Nullable java.lang.String inputMeasurements) {
    this.inputMeasurements = inputMeasurements;
    return this;
  }

  public void unsetInputMeasurements() {
    this.inputMeasurements = null;
  }

  /** Returns true if field inputMeasurements is set (has been assigned a value) and false otherwise */
  public boolean isSetInputMeasurements() {
    return this.inputMeasurements != null;
  }

  public void setInputMeasurementsIsSet(boolean value) {
    if (!value) {
      this.inputMeasurements = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOutputMeasurements() {
    return this.outputMeasurements;
  }

  public SimulationExecution setOutputMeasurements(@org.apache.thrift.annotation.Nullable java.lang.String outputMeasurements) {
    this.outputMeasurements = outputMeasurements;
    return this;
  }

  public void unsetOutputMeasurements() {
    this.outputMeasurements = null;
  }

  /** Returns true if field outputMeasurements is set (has been assigned a value) and false otherwise */
  public boolean isSetOutputMeasurements() {
    return this.outputMeasurements != null;
  }

  public void setOutputMeasurementsIsSet(boolean value) {
    if (!value) {
      this.outputMeasurements = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOutputTable() {
    return this.outputTable;
  }

  public SimulationExecution setOutputTable(@org.apache.thrift.annotation.Nullable java.lang.String outputTable) {
    this.outputTable = outputTable;
    return this;
  }

  public void unsetOutputTable() {
    this.outputTable = null;
  }

  /** Returns true if field outputTable is set (has been assigned a value) and false otherwise */
  public boolean isSetOutputTable() {
    return this.outputTable != null;
  }

  public void setOutputTableIsSet(boolean value) {
    if (!value) {
      this.outputTable = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getResult() {
    return this.result;
  }

  public SimulationExecution setResult(@org.apache.thrift.annotation.Nullable java.lang.String result) {
    this.result = result;
    return this;
  }

  public void unsetResult() {
    this.result = null;
  }

  /** Returns true if field result is set (has been assigned a value) and false otherwise */
  public boolean isSetResult() {
    return this.result != null;
  }

  public void setResultIsSet(boolean value) {
    if (!value) {
      this.result = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getError() {
    return this.error;
  }

  public SimulationExecution setError(@org.apache.thrift.annotation.Nullable java.lang.String error) {
    this.error = error;
    return this;
  }

  public void unsetError() {
    this.error = null;
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  public boolean isSetError() {
    return this.error != null;
  }

  public void setErrorIsSet(boolean value) {
    if (!value) {
      this.error = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getProcessLog() {
    return this.processLog;
  }

  public SimulationExecution setProcessLog(@org.apache.thrift.annotation.Nullable java.lang.String processLog) {
    this.processLog = processLog;
    return this;
  }

  public void unsetProcessLog() {
    this.processLog = null;
  }

  /** Returns true if field processLog is set (has been assigned a value) and false otherwise */
  public boolean isSetProcessLog() {
    return this.processLog != null;
  }

  public void setProcessLogIsSet(boolean value) {
    if (!value) {
      this.processLog = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TIMESTAMP:
      if (value == null) {
        unsetTimestamp();
      } else {
        setTimestamp((java.lang.Long)value);
      }
      break;

    case ARCHIVE_ID:
      if (value == null) {
        unsetArchiveId();
      } else {
        setArchiveId((java.lang.Long)value);
      }
      break;

    case ARCHIVE_NAME:
      if (value == null) {
        unsetArchiveName();
      } else {
        setArchiveName((java.lang.String)value);
      }
      break;

    case START_TIME:
      if (value == null) {
        unsetStartTime();
      } else {
        setStartTime((java.lang.Long)value);
      }
      break;

    case END_TIME:
      if (value == null) {
        unsetEndTime();
      } else {
        setEndTime((java.lang.Long)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((java.lang.String)value);
      }
      break;

    case INPUT_MEASUREMENTS:
      if (value == null) {
        unsetInputMeasurements();
      } else {
        setInputMeasurements((java.lang.String)value);
      }
      break;

    case OUTPUT_MEASUREMENTS:
      if (value == null) {
        unsetOutputMeasurements();
      } else {
        setOutputMeasurements((java.lang.String)value);
      }
      break;

    case OUTPUT_TABLE:
      if (value == null) {
        unsetOutputTable();
      } else {
        setOutputTable((java.lang.String)value);
      }
      break;

    case RESULT:
      if (value == null) {
        unsetResult();
      } else {
        setResult((java.lang.String)value);
      }
      break;

    case ERROR:
      if (value == null) {
        unsetError();
      } else {
        setError((java.lang.String)value);
      }
      break;

    case PROCESS_LOG:
      if (value == null) {
        unsetProcessLog();
      } else {
        setProcessLog((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TIMESTAMP:
      return getTimestamp();

    case ARCHIVE_ID:
      return getArchiveId();

    case ARCHIVE_NAME:
      return getArchiveName();

    case START_TIME:
      return getStartTime();

    case END_TIME:
      return getEndTime();

    case STATUS:
      return getStatus();

    case INPUT_MEASUREMENTS:
      return getInputMeasurements();

    case OUTPUT_MEASUREMENTS:
      return getOutputMeasurements();

    case OUTPUT_TABLE:
      return getOutputTable();

    case RESULT:
      return getResult();

    case ERROR:
      return getError();

    case PROCESS_LOG:
      return getProcessLog();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TIMESTAMP:
      return isSetTimestamp();
    case ARCHIVE_ID:
      return isSetArchiveId();
    case ARCHIVE_NAME:
      return isSetArchiveName();
    case START_TIME:
      return isSetStartTime();
    case END_TIME:
      return isSetEndTime();
    case STATUS:
      return isSetStatus();
    case INPUT_MEASUREMENTS:
      return isSetInputMeasurements();
    case OUTPUT_MEASUREMENTS:
      return isSetOutputMeasurements();
    case OUTPUT_TABLE:
      return isSetOutputTable();
    case RESULT:
      return isSetResult();
    case ERROR:
      return isSetError();
    case PROCESS_LOG:
      return isSetProcessLog();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof SimulationExecution)
      return this.equals((SimulationExecution)that);
    return false;
  }

  public boolean equals(SimulationExecution that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp))
        return false;
      if (this.timestamp != that.timestamp)
        return false;
    }

    boolean this_present_archiveId = true && this.isSetArchiveId();
    boolean that_present_archiveId = true && that.isSetArchiveId();
    if (this_present_archiveId || that_present_archiveId) {
      if (!(this_present_archiveId && that_present_archiveId))
        return false;
      if (this.archiveId != that.archiveId)
        return false;
    }

    boolean this_present_archiveName = true && this.isSetArchiveName();
    boolean that_present_archiveName = true && that.isSetArchiveName();
    if (this_present_archiveName || that_present_archiveName) {
      if (!(this_present_archiveName && that_present_archiveName))
        return false;
      if (!this.archiveName.equals(that.archiveName))
        return false;
    }

    boolean this_present_startTime = true && this.isSetStartTime();
    boolean that_present_startTime = true && that.isSetStartTime();
    if (this_present_startTime || that_present_startTime) {
      if (!(this_present_startTime && that_present_startTime))
        return false;
      if (this.startTime != that.startTime)
        return false;
    }

    boolean this_present_endTime = true && this.isSetEndTime();
    boolean that_present_endTime = true && that.isSetEndTime();
    if (this_present_endTime || that_present_endTime) {
      if (!(this_present_endTime && that_present_endTime))
        return false;
      if (this.endTime != that.endTime)
        return false;
    }

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_inputMeasurements = true && this.isSetInputMeasurements();
    boolean that_present_inputMeasurements = true && that.isSetInputMeasurements();
    if (this_present_inputMeasurements || that_present_inputMeasurements) {
      if (!(this_present_inputMeasurements && that_present_inputMeasurements))
        return false;
      if (!this.inputMeasurements.equals(that.inputMeasurements))
        return false;
    }

    boolean this_present_outputMeasurements = true && this.isSetOutputMeasurements();
    boolean that_present_outputMeasurements = true && that.isSetOutputMeasurements();
    if (this_present_outputMeasurements || that_present_outputMeasurements) {
      if (!(this_present_outputMeasurements && that_present_outputMeasurements))
        return false;
      if (!this.outputMeasurements.equals(that.outputMeasurements))
        return false;
    }

    boolean this_present_outputTable = true && this.isSetOutputTable();
    boolean that_present_outputTable = true && that.isSetOutputTable();
    if (this_present_outputTable || that_present_outputTable) {
      if (!(this_present_outputTable && that_present_outputTable))
        return false;
      if (!this.outputTable.equals(that.outputTable))
        return false;
    }

    boolean this_present_result = true && this.isSetResult();
    boolean that_present_result = true && that.isSetResult();
    if (this_present_result || that_present_result) {
      if (!(this_present_result && that_present_result))
        return false;
      if (!this.result.equals(that.result))
        return false;
    }

    boolean this_present_error = true && this.isSetError();
    boolean that_present_error = true && that.isSetError();
    if (this_present_error || that_present_error) {
      if (!(this_present_error && that_present_error))
        return false;
      if (!this.error.equals(that.error))
        return false;
    }

    boolean this_present_processLog = true && this.isSetProcessLog();
    boolean that_present_processLog = true && that.isSetProcessLog();
    if (this_present_processLog || that_present_processLog) {
      if (!(this_present_processLog && that_present_processLog))
        return false;
      if (!this.processLog.equals(that.processLog))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(timestamp);

    hashCode = hashCode * 8191 + ((isSetArchiveId()) ? 131071 : 524287);
    if (isSetArchiveId())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(archiveId);

    hashCode = hashCode * 8191 + ((isSetArchiveName()) ? 131071 : 524287);
    if (isSetArchiveName())
      hashCode = hashCode * 8191 + archiveName.hashCode();

    hashCode = hashCode * 8191 + ((isSetStartTime()) ? 131071 : 524287);
    if (isSetStartTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(startTime);

    hashCode = hashCode * 8191 + ((isSetEndTime()) ? 131071 : 524287);
    if (isSetEndTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(endTime);

    hashCode = hashCode * 8191 + ((isSetStatus()) ? 131071 : 524287);
    if (isSetStatus())
      hashCode = hashCode * 8191 + status.hashCode();

    hashCode = hashCode * 8191 + ((isSetInputMeasurements()) ? 131071 : 524287);
    if (isSetInputMeasurements())
      hashCode = hashCode * 8191 + inputMeasurements.hashCode();

    hashCode = hashCode * 8191 + ((isSetOutputMeasurements()) ? 131071 : 524287);
    if (isSetOutputMeasurements())
      hashCode = hashCode * 8191 + outputMeasurements.hashCode();

    hashCode = hashCode * 8191 + ((isSetOutputTable()) ? 131071 : 524287);
    if (isSetOutputTable())
      hashCode = hashCode * 8191 + outputTable.hashCode();

    hashCode = hashCode * 8191 + ((isSetResult()) ? 131071 : 524287);
    if (isSetResult())
      hashCode = hashCode * 8191 + result.hashCode();

    hashCode = hashCode * 8191 + ((isSetError()) ? 131071 : 524287);
    if (isSetError())
      hashCode = hashCode * 8191 + error.hashCode();

    hashCode = hashCode * 8191 + ((isSetProcessLog()) ? 131071 : 524287);
    if (isSetProcessLog())
      hashCode = hashCode * 8191 + processLog.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(SimulationExecution other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetTimestamp(), other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetArchiveId(), other.isSetArchiveId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetArchiveId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.archiveId, other.archiveId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetArchiveName(), other.isSetArchiveName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetArchiveName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.archiveName, other.archiveName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStartTime(), other.isSetStartTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStartTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.startTime, other.startTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEndTime(), other.isSetEndTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEndTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.endTime, other.endTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStatus(), other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetInputMeasurements(), other.isSetInputMeasurements());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInputMeasurements()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.inputMeasurements, other.inputMeasurements);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOutputMeasurements(), other.isSetOutputMeasurements());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutputMeasurements()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outputMeasurements, other.outputMeasurements);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOutputTable(), other.isSetOutputTable());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutputTable()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outputTable, other.outputTable);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetResult(), other.isSetResult());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResult()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.result, other.result);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetError(), other.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, other.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetProcessLog(), other.isSetProcessLog());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProcessLog()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.processLog, other.processLog);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SimulationExecution(");
    boolean first = true;

    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    if (isSetArchiveId()) {
      if (!first) sb.append(", ");
      sb.append("archiveId:");
      sb.append(this.archiveId);
      first = false;
    }
    if (isSetArchiveName()) {
      if (!first) sb.append(", ");
      sb.append("archiveName:");
      if (this.archiveName == null) {
        sb.append("null");
      } else {
        sb.append(this.archiveName);
      }
      first = false;
    }
    if (isSetStartTime()) {
      if (!first) sb.append(", ");
      sb.append("startTime:");
      sb.append(this.startTime);
      first = false;
    }
    if (isSetEndTime()) {
      if (!first) sb.append(", ");
      sb.append("endTime:");
      sb.append(this.endTime);
      first = false;
    }
    if (isSetStatus()) {
      if (!first) sb.append(", ");
      sb.append("status:");
      if (this.status == null) {
        sb.append("null");
      } else {
        sb.append(this.status);
      }
      first = false;
    }
    if (isSetInputMeasurements()) {
      if (!first) sb.append(", ");
      sb.append("inputMeasurements:");
      if (this.inputMeasurements == null) {
        sb.append("null");
      } else {
        sb.append(this.inputMeasurements);
      }
      first = false;
    }
    if (isSetOutputMeasurements()) {
      if (!first) sb.append(", ");
      sb.append("outputMeasurements:");
      if (this.outputMeasurements == null) {
        sb.append("null");
      } else {
        sb.append(this.outputMeasurements);
      }
      first = false;
    }
    if (isSetOutputTable()) {
      if (!first) sb.append(", ");
      sb.append("outputTable:");
      if (this.outputTable == null) {
        sb.append("null");
      } else {
        sb.append(this.outputTable);
      }
      first = false;
    }
    if (isSetResult()) {
      if (!first) sb.append(", ");
      sb.append("result:");
      if (this.result == null) {
        sb.append("null");
      } else {
        sb.append(this.result);
      }
      first = false;
    }
    if (isSetError()) {
      if (!first) sb.append(", ");
      sb.append("error:");
      if (this.error == null) {
        sb.append("null");
      } else {
        sb.append(this.error);
      }
      first = false;
    }
    if (isSetProcessLog()) {
      if (!first) sb.append(", ");
      sb.append("processLog:");
      if (this.processLog == null) {
        sb.append("null");
      } else {
        sb.append(this.processLog);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SimulationExecutionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SimulationExecutionStandardScheme getScheme() {
      return new SimulationExecutionStandardScheme();
    }
  }

  private static class SimulationExecutionStandardScheme extends org.apache.thrift.scheme.StandardScheme<SimulationExecution> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, SimulationExecution struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ARCHIVE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.archiveId = iprot.readI64();
              struct.setArchiveIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ARCHIVE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.archiveName = iprot.readString();
              struct.setArchiveNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // START_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.startTime = iprot.readI64();
              struct.setStartTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // END_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.endTime = iprot.readI64();
              struct.setEndTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.status = iprot.readString();
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // INPUT_MEASUREMENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.inputMeasurements = iprot.readString();
              struct.setInputMeasurementsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // OUTPUT_MEASUREMENTS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.outputMeasurements = iprot.readString();
              struct.setOutputMeasurementsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // OUTPUT_TABLE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.outputTable = iprot.readString();
              struct.setOutputTableIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // RESULT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.result = iprot.readString();
              struct.setResultIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.error = iprot.readString();
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // PROCESS_LOG
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.processLog = iprot.readString();
              struct.setProcessLogIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, SimulationExecution struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      if (struct.isSetArchiveId()) {
        oprot.writeFieldBegin(ARCHIVE_ID_FIELD_DESC);
        oprot.writeI64(struct.archiveId);
        oprot.writeFieldEnd();
      }
      if (struct.archiveName != null) {
        if (struct.isSetArchiveName()) {
          oprot.writeFieldBegin(ARCHIVE_NAME_FIELD_DESC);
          oprot.writeString(struct.archiveName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetStartTime()) {
        oprot.writeFieldBegin(START_TIME_FIELD_DESC);
        oprot.writeI64(struct.startTime);
        oprot.writeFieldEnd();
      }
      if (struct.isSetEndTime()) {
        oprot.writeFieldBegin(END_TIME_FIELD_DESC);
        oprot.writeI64(struct.endTime);
        oprot.writeFieldEnd();
      }
      if (struct.status != null) {
        if (struct.isSetStatus()) {
          oprot.writeFieldBegin(STATUS_FIELD_DESC);
          oprot.writeString(struct.status);
          oprot.writeFieldEnd();
        }
      }
      if (struct.inputMeasurements != null) {
        if (struct.isSetInputMeasurements()) {
          oprot.writeFieldBegin(INPUT_MEASUREMENTS_FIELD_DESC);
          oprot.writeString(struct.inputMeasurements);
          oprot.writeFieldEnd();
        }
      }
      if (struct.outputMeasurements != null) {
        if (struct.isSetOutputMeasurements()) {
          oprot.writeFieldBegin(OUTPUT_MEASUREMENTS_FIELD_DESC);
          oprot.writeString(struct.outputMeasurements);
          oprot.writeFieldEnd();
        }
      }
      if (struct.outputTable != null) {
        if (struct.isSetOutputTable()) {
          oprot.writeFieldBegin(OUTPUT_TABLE_FIELD_DESC);
          oprot.writeString(struct.outputTable);
          oprot.writeFieldEnd();
        }
      }
      if (struct.result != null) {
        if (struct.isSetResult()) {
          oprot.writeFieldBegin(RESULT_FIELD_DESC);
          oprot.writeString(struct.result);
          oprot.writeFieldEnd();
        }
      }
      if (struct.error != null) {
        if (struct.isSetError()) {
          oprot.writeFieldBegin(ERROR_FIELD_DESC);
          oprot.writeString(struct.error);
          oprot.writeFieldEnd();
        }
      }
      if (struct.processLog != null) {
        if (struct.isSetProcessLog()) {
          oprot.writeFieldBegin(PROCESS_LOG_FIELD_DESC);
          oprot.writeString(struct.processLog);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SimulationExecutionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public SimulationExecutionTupleScheme getScheme() {
      return new SimulationExecutionTupleScheme();
    }
  }

  private static class SimulationExecutionTupleScheme extends org.apache.thrift.scheme.TupleScheme<SimulationExecution> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SimulationExecution struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTimestamp()) {
        optionals.set(0);
      }
      if (struct.isSetArchiveId()) {
        optionals.set(1);
      }
      if (struct.isSetArchiveName()) {
        optionals.set(2);
      }
      if (struct.isSetStartTime()) {
        optionals.set(3);
      }
      if (struct.isSetEndTime()) {
        optionals.set(4);
      }
      if (struct.isSetStatus()) {
        optionals.set(5);
      }
      if (struct.isSetInputMeasurements()) {
        optionals.set(6);
      }
      if (struct.isSetOutputMeasurements()) {
        optionals.set(7);
      }
      if (struct.isSetOutputTable()) {
        optionals.set(8);
      }
      if (struct.isSetResult()) {
        optionals.set(9);
      }
      if (struct.isSetError()) {
        optionals.set(10);
      }
      if (struct.isSetProcessLog()) {
        optionals.set(11);
      }
      oprot.writeBitSet(optionals, 12);
      if (struct.isSetTimestamp()) {
        oprot.writeI64(struct.timestamp);
      }
      if (struct.isSetArchiveId()) {
        oprot.writeI64(struct.archiveId);
      }
      if (struct.isSetArchiveName()) {
        oprot.writeString(struct.archiveName);
      }
      if (struct.isSetStartTime()) {
        oprot.writeI64(struct.startTime);
      }
      if (struct.isSetEndTime()) {
        oprot.writeI64(struct.endTime);
      }
      if (struct.isSetStatus()) {
        oprot.writeString(struct.status);
      }
      if (struct.isSetInputMeasurements()) {
        oprot.writeString(struct.inputMeasurements);
      }
      if (struct.isSetOutputMeasurements()) {
        oprot.writeString(struct.outputMeasurements);
      }
      if (struct.isSetOutputTable()) {
        oprot.writeString(struct.outputTable);
      }
      if (struct.isSetResult()) {
        oprot.writeString(struct.result);
      }
      if (struct.isSetError()) {
        oprot.writeString(struct.error);
      }
      if (struct.isSetProcessLog()) {
        oprot.writeString(struct.processLog);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SimulationExecution struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(12);
      if (incoming.get(0)) {
        struct.timestamp = iprot.readI64();
        struct.setTimestampIsSet(true);
      }
      if (incoming.get(1)) {
        struct.archiveId = iprot.readI64();
        struct.setArchiveIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.archiveName = iprot.readString();
        struct.setArchiveNameIsSet(true);
      }
      if (incoming.get(3)) {
        struct.startTime = iprot.readI64();
        struct.setStartTimeIsSet(true);
      }
      if (incoming.get(4)) {
        struct.endTime = iprot.readI64();
        struct.setEndTimeIsSet(true);
      }
      if (incoming.get(5)) {
        struct.status = iprot.readString();
        struct.setStatusIsSet(true);
      }
      if (incoming.get(6)) {
        struct.inputMeasurements = iprot.readString();
        struct.setInputMeasurementsIsSet(true);
      }
      if (incoming.get(7)) {
        struct.outputMeasurements = iprot.readString();
        struct.setOutputMeasurementsIsSet(true);
      }
      if (incoming.get(8)) {
        struct.outputTable = iprot.readString();
        struct.setOutputTableIsSet(true);
      }
      if (incoming.get(9)) {
        struct.result = iprot.readString();
        struct.setResultIsSet(true);
      }
      if (incoming.get(10)) {
        struct.error = iprot.readString();
        struct.setErrorIsSet(true);
      }
      if (incoming.get(11)) {
        struct.processLog = iprot.readString();
        struct.setProcessLogIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

