// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"tsinghua/api"
)

var _ = api.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  Result saveAssociationRule(AssociationRule rule)")
	fmt.Fprintln(os.Stderr, "  Result queryAssociationRules(AssociationRulesQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countAssociationRules(AssociationRulesQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getAssociationRule(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result deleteAssociationRule(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result registerDataSource(string jsonBody)")
	fmt.Fprintln(os.Stderr, "  Result removeDataSource(StorageEngineInfo storageEngineInfo)")
	fmt.Fprintln(os.Stderr, "  Result listDataSources()")
	fmt.Fprintln(os.Stderr, "  Result getDataSourceTree()")
	fmt.Fprintln(os.Stderr, "  Result queryData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result deleteData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result queryRelationalData(RelationalQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countRelationalData(RelationalQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result saveModelMeta(ModelMeta modelMeta)")
	fmt.Fprintln(os.Stderr, "  Result getModelMeta(string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result getModelHistory(string name)")
	fmt.Fprintln(os.Stderr, "  Result deleteModel(string name, string version)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()
	
	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}
	
	cmd := flag.Arg(0)
	var err error
	var cfg *thrift.TConfiguration = nil
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransportConf(trans, cfg)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := api.NewApiServiceClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}
	
	switch cmd {
	case "saveAssociationRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveAssociationRule requires 1 args")
			flag.Usage()
		}
		arg115 := flag.Arg(1)
		mbTrans116 := thrift.NewTMemoryBufferLen(len(arg115))
		defer mbTrans116.Close()
		_, err117 := mbTrans116.WriteString(arg115)
		if err117 != nil {
			Usage()
			return
		}
		factory118 := thrift.NewTJSONProtocolFactory()
		jsProt119 := factory118.GetProtocol(mbTrans116)
		argvalue0 := api.NewAssociationRule()
		err120 := argvalue0.Read(context.Background(), jsProt119)
		if err120 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveAssociationRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryAssociationRules":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryAssociationRules requires 1 args")
			flag.Usage()
		}
		arg121 := flag.Arg(1)
		mbTrans122 := thrift.NewTMemoryBufferLen(len(arg121))
		defer mbTrans122.Close()
		_, err123 := mbTrans122.WriteString(arg121)
		if err123 != nil {
			Usage()
			return
		}
		factory124 := thrift.NewTJSONProtocolFactory()
		jsProt125 := factory124.GetProtocol(mbTrans122)
		argvalue0 := api.NewAssociationRulesQueryRequest()
		err126 := argvalue0.Read(context.Background(), jsProt125)
		if err126 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryAssociationRules(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countAssociationRules":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountAssociationRules requires 1 args")
			flag.Usage()
		}
		arg127 := flag.Arg(1)
		mbTrans128 := thrift.NewTMemoryBufferLen(len(arg127))
		defer mbTrans128.Close()
		_, err129 := mbTrans128.WriteString(arg127)
		if err129 != nil {
			Usage()
			return
		}
		factory130 := thrift.NewTJSONProtocolFactory()
		jsProt131 := factory130.GetProtocol(mbTrans128)
		argvalue0 := api.NewAssociationRulesQueryRequest()
		err132 := argvalue0.Read(context.Background(), jsProt131)
		if err132 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountAssociationRules(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getAssociationRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetAssociationRule requires 1 args")
			flag.Usage()
		}
		argvalue0, err133 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err133 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetAssociationRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteAssociationRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteAssociationRule requires 1 args")
			flag.Usage()
		}
		argvalue0, err134 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err134 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteAssociationRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "registerDataSource":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RegisterDataSource requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.RegisterDataSource(context.Background(), value0))
		fmt.Print("\n")
		break
	case "removeDataSource":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RemoveDataSource requires 1 args")
			flag.Usage()
		}
		arg136 := flag.Arg(1)
		mbTrans137 := thrift.NewTMemoryBufferLen(len(arg136))
		defer mbTrans137.Close()
		_, err138 := mbTrans137.WriteString(arg136)
		if err138 != nil {
			Usage()
			return
		}
		factory139 := thrift.NewTJSONProtocolFactory()
		jsProt140 := factory139.GetProtocol(mbTrans137)
		argvalue0 := api.NewStorageEngineInfo()
		err141 := argvalue0.Read(context.Background(), jsProt140)
		if err141 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RemoveDataSource(context.Background(), value0))
		fmt.Print("\n")
		break
	case "listDataSources":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "ListDataSources requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ListDataSources(context.Background()))
		fmt.Print("\n")
		break
	case "getDataSourceTree":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetDataSourceTree requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetDataSourceTree(context.Background()))
		fmt.Print("\n")
		break
	case "queryData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryData requires 1 args")
			flag.Usage()
		}
		arg142 := flag.Arg(1)
		mbTrans143 := thrift.NewTMemoryBufferLen(len(arg142))
		defer mbTrans143.Close()
		_, err144 := mbTrans143.WriteString(arg142)
		if err144 != nil {
			Usage()
			return
		}
		factory145 := thrift.NewTJSONProtocolFactory()
		jsProt146 := factory145.GetProtocol(mbTrans143)
		argvalue0 := api.NewDataQueryRequest()
		err147 := argvalue0.Read(context.Background(), jsProt146)
		if err147 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteData requires 1 args")
			flag.Usage()
		}
		arg148 := flag.Arg(1)
		mbTrans149 := thrift.NewTMemoryBufferLen(len(arg148))
		defer mbTrans149.Close()
		_, err150 := mbTrans149.WriteString(arg148)
		if err150 != nil {
			Usage()
			return
		}
		factory151 := thrift.NewTJSONProtocolFactory()
		jsProt152 := factory151.GetProtocol(mbTrans149)
		argvalue0 := api.NewDataQueryRequest()
		err153 := argvalue0.Read(context.Background(), jsProt152)
		if err153 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryRelationalData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryRelationalData requires 1 args")
			flag.Usage()
		}
		arg154 := flag.Arg(1)
		mbTrans155 := thrift.NewTMemoryBufferLen(len(arg154))
		defer mbTrans155.Close()
		_, err156 := mbTrans155.WriteString(arg154)
		if err156 != nil {
			Usage()
			return
		}
		factory157 := thrift.NewTJSONProtocolFactory()
		jsProt158 := factory157.GetProtocol(mbTrans155)
		argvalue0 := api.NewRelationalQueryRequest()
		err159 := argvalue0.Read(context.Background(), jsProt158)
		if err159 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryRelationalData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countRelationalData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountRelationalData requires 1 args")
			flag.Usage()
		}
		arg160 := flag.Arg(1)
		mbTrans161 := thrift.NewTMemoryBufferLen(len(arg160))
		defer mbTrans161.Close()
		_, err162 := mbTrans161.WriteString(arg160)
		if err162 != nil {
			Usage()
			return
		}
		factory163 := thrift.NewTJSONProtocolFactory()
		jsProt164 := factory163.GetProtocol(mbTrans161)
		argvalue0 := api.NewRelationalQueryRequest()
		err165 := argvalue0.Read(context.Background(), jsProt164)
		if err165 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountRelationalData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "saveModelMeta":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveModelMeta requires 1 args")
			flag.Usage()
		}
		arg166 := flag.Arg(1)
		mbTrans167 := thrift.NewTMemoryBufferLen(len(arg166))
		defer mbTrans167.Close()
		_, err168 := mbTrans167.WriteString(arg166)
		if err168 != nil {
			Usage()
			return
		}
		factory169 := thrift.NewTJSONProtocolFactory()
		jsProt170 := factory169.GetProtocol(mbTrans167)
		argvalue0 := api.NewModelMeta()
		err171 := argvalue0.Read(context.Background(), jsProt170)
		if err171 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveModelMeta(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getModelMeta":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetModelMeta requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetModelMeta(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "getModelHistory":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetModelHistory requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetModelHistory(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteModel":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DeleteModel requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.DeleteModel(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "":
		Usage()
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
