// Code generated by Thrift Compiler (0.22.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"tsinghua/api"
)

var _ = api.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  Result saveAssociationRule(AssociationRule rule)")
	fmt.Fprintln(os.Stderr, "  Result queryAssociationRules(AssociationRulesQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countAssociationRules(AssociationRulesQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getAssociationRule(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result deleteAssociationRule(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result validateAssociationRuleName(string name)")
	fmt.Fprintln(os.Stderr, "  Result saveParsingRule(ParsingRule rule)")
	fmt.Fprintln(os.Stderr, "  Result queryParsingRules(ParsingRulesQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countParsingRules(ParsingRulesQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getParsingRule(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result deleteParsingRule(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result validateParsingRuleName(string name)")
	fmt.Fprintln(os.Stderr, "  Result autoParseSourceCode(AutoParseRequest request)")
	fmt.Fprintln(os.Stderr, "  Result runTask(RunTaskRequest runTaskRequest)")
	fmt.Fprintln(os.Stderr, "  Result validateTaskUniqueness(RunTaskRequest request)")
	fmt.Fprintln(os.Stderr, "  Result stopTask(i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result getTaskLog(i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result queryTasks(RunTaskQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countTasks(RunTaskQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getTask(i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result deleteTask(i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result uploadReport(string file, i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result packageDownload(i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result getTimeRange(TimeRangeRequest request)")
	fmt.Fprintln(os.Stderr, "  Result registerDataSource(string jsonBody)")
	fmt.Fprintln(os.Stderr, "  Result removeDataSource(StorageEngineInfo storageEngineInfo)")
	fmt.Fprintln(os.Stderr, "  Result listDataSources()")
	fmt.Fprintln(os.Stderr, "  Result getDataSourceTree()")
	fmt.Fprintln(os.Stderr, "  Result queryData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result importData(string config, string file)")
	fmt.Fprintln(os.Stderr, "  Result exportData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result deleteData(DataQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result queryRelationalData(RelationalQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countRelationalData(RelationalQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result exportRelationalData(RelationalQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result uploadModel(string file, string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result downloadModel(string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result getModelMeta(string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result saveModelMeta(ModelMeta modelMeta)")
	fmt.Fprintln(os.Stderr, "  Result getModelHistory(string name)")
	fmt.Fprintln(os.Stderr, "  Result deleteModel(string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result getModelTree(string projectName)")
	fmt.Fprintln(os.Stderr, "  Result queryModelArchives(ModelArchiveQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countModelArchives(ModelArchiveQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result extractModelFile(ExtractModelFileRequest request)")
	fmt.Fprintln(os.Stderr, "  Result uploadAlgorithm(string file, string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result downloadAlgorithm(string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result getAlgorithmMeta(string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result saveAlgorithmMeta(AlgorithmMeta algorithmMeta)")
	fmt.Fprintln(os.Stderr, "  Result getAlgorithmHistory(string name)")
	fmt.Fprintln(os.Stderr, "  Result deleteAlgorithm(string name, string version)")
	fmt.Fprintln(os.Stderr, "  Result getAlgorithmTree(string projectName)")
	fmt.Fprintln(os.Stderr, "  Result queryAlgorithmArchives(AlgorithmArchiveQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countAlgorithmArchives(AlgorithmArchiveQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result extractAlgorithmFile(ExtractAlgorithmFileRequest request)")
	fmt.Fprintln(os.Stderr, "  Result queryDataArchives(DataArchiveQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getDataArchiveDetail(string name)")
	fmt.Fprintln(os.Stderr, "  Result countDataArchives(DataArchiveQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result deleteDataArchive(DataArchiveQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result updateDataArchive(DataArchive archive)")
	fmt.Fprintln(os.Stderr, "  Result createProject(Project project)")
	fmt.Fprintln(os.Stderr, "  Result queryProjects(ProjectsQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countProjects(ProjectsQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getProject(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result getProjectTree(string name)")
	fmt.Fprintln(os.Stderr, "  Result importProject(string file, string projectName)")
	fmt.Fprintln(os.Stderr, "  Result exportProject(ProjectExportRequest request)")
	fmt.Fprintln(os.Stderr, "  Result saveSimulationArchive(SimulationArchive archive)")
	fmt.Fprintln(os.Stderr, "  Result querySimulationArchives(string name, string projectName, string owner, bool status, i32 pageNum, i32 pageSize)")
	fmt.Fprintln(os.Stderr, "  Result countSimulationArchives(string name, string projectName, string owner, bool status)")
	fmt.Fprintln(os.Stderr, "  Result getSimulationArchive(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result deleteSimulationArchive(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result validateSimulationArchiveName(string name)")
	fmt.Fprintln(os.Stderr, "  Result copySimulationArchive(i64 createTime, string newName)")
	fmt.Fprintln(os.Stderr, "  Result runSimulation(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result runSimulationSelective(RunSimulationSelectiveRequest request)")
	fmt.Fprintln(os.Stderr, "  Result stopSimulation(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result getSimulationExecutionStatus(i64 createTime)")
	fmt.Fprintln(os.Stderr, "  Result getSimulationExecutionLog(i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result querySimulationExecutionRecords(ExecutionRecordQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countSimulationExecutionRecords(ExecutionRecordQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result deleteSimulationExecutionRecord(i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result uploadSimulationReport(string file, i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result simulationPackageDownload(i64 timestamp)")
	fmt.Fprintln(os.Stderr, "  Result login(LoginRequest loginRequest)")
	fmt.Fprintln(os.Stderr, "  Result refreshToken(RefreshTokenRequest request)")
	fmt.Fprintln(os.Stderr, "  Result verifyToken(string token)")
	fmt.Fprintln(os.Stderr, "  Result logout()")
	fmt.Fprintln(os.Stderr, "  Result getCurrentAuthUser()")
	fmt.Fprintln(os.Stderr, "  Result saveUser(User user)")
	fmt.Fprintln(os.Stderr, "  Result queryUsers(UserQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countUsers(UserQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result allUsers()")
	fmt.Fprintln(os.Stderr, "  Result getUser(string username)")
	fmt.Fprintln(os.Stderr, "  Result deleteUser(string username)")
	fmt.Fprintln(os.Stderr, "  Result updateUser(User user)")
	fmt.Fprintln(os.Stderr, "  Result getRoles()")
	fmt.Fprintln(os.Stderr, "  Result changePassword(ChangePasswordRequest request)")
	fmt.Fprintln(os.Stderr, "  Result getCurrentUser()")
	fmt.Fprintln(os.Stderr, "  Result listOwnerTables()")
	fmt.Fprintln(os.Stderr, "  Result queryDataPermissions(DataPermissionQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result countDataPermissions(DataPermissionQueryRequest request)")
	fmt.Fprintln(os.Stderr, "  Result updateDataPermission(DataPermissionUpdateRequest request)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()
	
	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}
	
	cmd := flag.Arg(0)
	var err error
	var cfg *thrift.TConfiguration = nil
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransportConf(trans, cfg)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := api.NewApiServiceClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}
	
	switch cmd {
	case "saveAssociationRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveAssociationRule requires 1 args")
			flag.Usage()
		}
		arg641 := flag.Arg(1)
		mbTrans642 := thrift.NewTMemoryBufferLen(len(arg641))
		defer mbTrans642.Close()
		_, err643 := mbTrans642.WriteString(arg641)
		if err643 != nil {
			Usage()
			return
		}
		factory644 := thrift.NewTJSONProtocolFactory()
		jsProt645 := factory644.GetProtocol(mbTrans642)
		argvalue0 := api.NewAssociationRule()
		err646 := argvalue0.Read(context.Background(), jsProt645)
		if err646 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveAssociationRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryAssociationRules":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryAssociationRules requires 1 args")
			flag.Usage()
		}
		arg647 := flag.Arg(1)
		mbTrans648 := thrift.NewTMemoryBufferLen(len(arg647))
		defer mbTrans648.Close()
		_, err649 := mbTrans648.WriteString(arg647)
		if err649 != nil {
			Usage()
			return
		}
		factory650 := thrift.NewTJSONProtocolFactory()
		jsProt651 := factory650.GetProtocol(mbTrans648)
		argvalue0 := api.NewAssociationRulesQueryRequest()
		err652 := argvalue0.Read(context.Background(), jsProt651)
		if err652 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryAssociationRules(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countAssociationRules":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountAssociationRules requires 1 args")
			flag.Usage()
		}
		arg653 := flag.Arg(1)
		mbTrans654 := thrift.NewTMemoryBufferLen(len(arg653))
		defer mbTrans654.Close()
		_, err655 := mbTrans654.WriteString(arg653)
		if err655 != nil {
			Usage()
			return
		}
		factory656 := thrift.NewTJSONProtocolFactory()
		jsProt657 := factory656.GetProtocol(mbTrans654)
		argvalue0 := api.NewAssociationRulesQueryRequest()
		err658 := argvalue0.Read(context.Background(), jsProt657)
		if err658 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountAssociationRules(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getAssociationRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetAssociationRule requires 1 args")
			flag.Usage()
		}
		argvalue0, err659 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err659 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetAssociationRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteAssociationRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteAssociationRule requires 1 args")
			flag.Usage()
		}
		argvalue0, err660 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err660 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteAssociationRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "validateAssociationRuleName":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ValidateAssociationRuleName requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ValidateAssociationRuleName(context.Background(), value0))
		fmt.Print("\n")
		break
	case "saveParsingRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveParsingRule requires 1 args")
			flag.Usage()
		}
		arg662 := flag.Arg(1)
		mbTrans663 := thrift.NewTMemoryBufferLen(len(arg662))
		defer mbTrans663.Close()
		_, err664 := mbTrans663.WriteString(arg662)
		if err664 != nil {
			Usage()
			return
		}
		factory665 := thrift.NewTJSONProtocolFactory()
		jsProt666 := factory665.GetProtocol(mbTrans663)
		argvalue0 := api.NewParsingRule()
		err667 := argvalue0.Read(context.Background(), jsProt666)
		if err667 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveParsingRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryParsingRules":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryParsingRules requires 1 args")
			flag.Usage()
		}
		arg668 := flag.Arg(1)
		mbTrans669 := thrift.NewTMemoryBufferLen(len(arg668))
		defer mbTrans669.Close()
		_, err670 := mbTrans669.WriteString(arg668)
		if err670 != nil {
			Usage()
			return
		}
		factory671 := thrift.NewTJSONProtocolFactory()
		jsProt672 := factory671.GetProtocol(mbTrans669)
		argvalue0 := api.NewParsingRulesQueryRequest()
		err673 := argvalue0.Read(context.Background(), jsProt672)
		if err673 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryParsingRules(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countParsingRules":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountParsingRules requires 1 args")
			flag.Usage()
		}
		arg674 := flag.Arg(1)
		mbTrans675 := thrift.NewTMemoryBufferLen(len(arg674))
		defer mbTrans675.Close()
		_, err676 := mbTrans675.WriteString(arg674)
		if err676 != nil {
			Usage()
			return
		}
		factory677 := thrift.NewTJSONProtocolFactory()
		jsProt678 := factory677.GetProtocol(mbTrans675)
		argvalue0 := api.NewParsingRulesQueryRequest()
		err679 := argvalue0.Read(context.Background(), jsProt678)
		if err679 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountParsingRules(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getParsingRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetParsingRule requires 1 args")
			flag.Usage()
		}
		argvalue0, err680 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err680 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetParsingRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteParsingRule":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteParsingRule requires 1 args")
			flag.Usage()
		}
		argvalue0, err681 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err681 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteParsingRule(context.Background(), value0))
		fmt.Print("\n")
		break
	case "validateParsingRuleName":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ValidateParsingRuleName requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ValidateParsingRuleName(context.Background(), value0))
		fmt.Print("\n")
		break
	case "autoParseSourceCode":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "AutoParseSourceCode requires 1 args")
			flag.Usage()
		}
		arg683 := flag.Arg(1)
		mbTrans684 := thrift.NewTMemoryBufferLen(len(arg683))
		defer mbTrans684.Close()
		_, err685 := mbTrans684.WriteString(arg683)
		if err685 != nil {
			Usage()
			return
		}
		factory686 := thrift.NewTJSONProtocolFactory()
		jsProt687 := factory686.GetProtocol(mbTrans684)
		argvalue0 := api.NewAutoParseRequest()
		err688 := argvalue0.Read(context.Background(), jsProt687)
		if err688 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.AutoParseSourceCode(context.Background(), value0))
		fmt.Print("\n")
		break
	case "runTask":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RunTask requires 1 args")
			flag.Usage()
		}
		arg689 := flag.Arg(1)
		mbTrans690 := thrift.NewTMemoryBufferLen(len(arg689))
		defer mbTrans690.Close()
		_, err691 := mbTrans690.WriteString(arg689)
		if err691 != nil {
			Usage()
			return
		}
		factory692 := thrift.NewTJSONProtocolFactory()
		jsProt693 := factory692.GetProtocol(mbTrans690)
		argvalue0 := api.NewRunTaskRequest()
		err694 := argvalue0.Read(context.Background(), jsProt693)
		if err694 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RunTask(context.Background(), value0))
		fmt.Print("\n")
		break
	case "validateTaskUniqueness":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ValidateTaskUniqueness requires 1 args")
			flag.Usage()
		}
		arg695 := flag.Arg(1)
		mbTrans696 := thrift.NewTMemoryBufferLen(len(arg695))
		defer mbTrans696.Close()
		_, err697 := mbTrans696.WriteString(arg695)
		if err697 != nil {
			Usage()
			return
		}
		factory698 := thrift.NewTJSONProtocolFactory()
		jsProt699 := factory698.GetProtocol(mbTrans696)
		argvalue0 := api.NewRunTaskRequest()
		err700 := argvalue0.Read(context.Background(), jsProt699)
		if err700 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ValidateTaskUniqueness(context.Background(), value0))
		fmt.Print("\n")
		break
	case "stopTask":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "StopTask requires 1 args")
			flag.Usage()
		}
		argvalue0, err701 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err701 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.StopTask(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getTaskLog":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTaskLog requires 1 args")
			flag.Usage()
		}
		argvalue0, err702 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err702 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetTaskLog(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryTasks":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryTasks requires 1 args")
			flag.Usage()
		}
		arg703 := flag.Arg(1)
		mbTrans704 := thrift.NewTMemoryBufferLen(len(arg703))
		defer mbTrans704.Close()
		_, err705 := mbTrans704.WriteString(arg703)
		if err705 != nil {
			Usage()
			return
		}
		factory706 := thrift.NewTJSONProtocolFactory()
		jsProt707 := factory706.GetProtocol(mbTrans704)
		argvalue0 := api.NewRunTaskQueryRequest()
		err708 := argvalue0.Read(context.Background(), jsProt707)
		if err708 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryTasks(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countTasks":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountTasks requires 1 args")
			flag.Usage()
		}
		arg709 := flag.Arg(1)
		mbTrans710 := thrift.NewTMemoryBufferLen(len(arg709))
		defer mbTrans710.Close()
		_, err711 := mbTrans710.WriteString(arg709)
		if err711 != nil {
			Usage()
			return
		}
		factory712 := thrift.NewTJSONProtocolFactory()
		jsProt713 := factory712.GetProtocol(mbTrans710)
		argvalue0 := api.NewRunTaskQueryRequest()
		err714 := argvalue0.Read(context.Background(), jsProt713)
		if err714 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountTasks(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getTask":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTask requires 1 args")
			flag.Usage()
		}
		argvalue0, err715 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err715 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetTask(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteTask":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteTask requires 1 args")
			flag.Usage()
		}
		argvalue0, err716 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err716 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteTask(context.Background(), value0))
		fmt.Print("\n")
		break
	case "uploadReport":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "UploadReport requires 2 args")
			flag.Usage()
		}
		argvalue0 := []byte(flag.Arg(1))
		value0 := argvalue0
		argvalue1, err718 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err718 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.UploadReport(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "packageDownload":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "PackageDownload requires 1 args")
			flag.Usage()
		}
		argvalue0, err719 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err719 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.PackageDownload(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getTimeRange":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTimeRange requires 1 args")
			flag.Usage()
		}
		arg720 := flag.Arg(1)
		mbTrans721 := thrift.NewTMemoryBufferLen(len(arg720))
		defer mbTrans721.Close()
		_, err722 := mbTrans721.WriteString(arg720)
		if err722 != nil {
			Usage()
			return
		}
		factory723 := thrift.NewTJSONProtocolFactory()
		jsProt724 := factory723.GetProtocol(mbTrans721)
		argvalue0 := api.NewTimeRangeRequest()
		err725 := argvalue0.Read(context.Background(), jsProt724)
		if err725 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetTimeRange(context.Background(), value0))
		fmt.Print("\n")
		break
	case "registerDataSource":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RegisterDataSource requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.RegisterDataSource(context.Background(), value0))
		fmt.Print("\n")
		break
	case "removeDataSource":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RemoveDataSource requires 1 args")
			flag.Usage()
		}
		arg727 := flag.Arg(1)
		mbTrans728 := thrift.NewTMemoryBufferLen(len(arg727))
		defer mbTrans728.Close()
		_, err729 := mbTrans728.WriteString(arg727)
		if err729 != nil {
			Usage()
			return
		}
		factory730 := thrift.NewTJSONProtocolFactory()
		jsProt731 := factory730.GetProtocol(mbTrans728)
		argvalue0 := api.NewStorageEngineInfo()
		err732 := argvalue0.Read(context.Background(), jsProt731)
		if err732 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RemoveDataSource(context.Background(), value0))
		fmt.Print("\n")
		break
	case "listDataSources":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "ListDataSources requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ListDataSources(context.Background()))
		fmt.Print("\n")
		break
	case "getDataSourceTree":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetDataSourceTree requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetDataSourceTree(context.Background()))
		fmt.Print("\n")
		break
	case "queryData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryData requires 1 args")
			flag.Usage()
		}
		arg733 := flag.Arg(1)
		mbTrans734 := thrift.NewTMemoryBufferLen(len(arg733))
		defer mbTrans734.Close()
		_, err735 := mbTrans734.WriteString(arg733)
		if err735 != nil {
			Usage()
			return
		}
		factory736 := thrift.NewTJSONProtocolFactory()
		jsProt737 := factory736.GetProtocol(mbTrans734)
		argvalue0 := api.NewDataQueryRequest()
		err738 := argvalue0.Read(context.Background(), jsProt737)
		if err738 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "importData":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "ImportData requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := []byte(flag.Arg(2))
		value1 := argvalue1
		fmt.Print(client.ImportData(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "exportData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ExportData requires 1 args")
			flag.Usage()
		}
		arg741 := flag.Arg(1)
		mbTrans742 := thrift.NewTMemoryBufferLen(len(arg741))
		defer mbTrans742.Close()
		_, err743 := mbTrans742.WriteString(arg741)
		if err743 != nil {
			Usage()
			return
		}
		factory744 := thrift.NewTJSONProtocolFactory()
		jsProt745 := factory744.GetProtocol(mbTrans742)
		argvalue0 := api.NewDataQueryRequest()
		err746 := argvalue0.Read(context.Background(), jsProt745)
		if err746 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ExportData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteData requires 1 args")
			flag.Usage()
		}
		arg747 := flag.Arg(1)
		mbTrans748 := thrift.NewTMemoryBufferLen(len(arg747))
		defer mbTrans748.Close()
		_, err749 := mbTrans748.WriteString(arg747)
		if err749 != nil {
			Usage()
			return
		}
		factory750 := thrift.NewTJSONProtocolFactory()
		jsProt751 := factory750.GetProtocol(mbTrans748)
		argvalue0 := api.NewDataQueryRequest()
		err752 := argvalue0.Read(context.Background(), jsProt751)
		if err752 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryRelationalData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryRelationalData requires 1 args")
			flag.Usage()
		}
		arg753 := flag.Arg(1)
		mbTrans754 := thrift.NewTMemoryBufferLen(len(arg753))
		defer mbTrans754.Close()
		_, err755 := mbTrans754.WriteString(arg753)
		if err755 != nil {
			Usage()
			return
		}
		factory756 := thrift.NewTJSONProtocolFactory()
		jsProt757 := factory756.GetProtocol(mbTrans754)
		argvalue0 := api.NewRelationalQueryRequest()
		err758 := argvalue0.Read(context.Background(), jsProt757)
		if err758 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryRelationalData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countRelationalData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountRelationalData requires 1 args")
			flag.Usage()
		}
		arg759 := flag.Arg(1)
		mbTrans760 := thrift.NewTMemoryBufferLen(len(arg759))
		defer mbTrans760.Close()
		_, err761 := mbTrans760.WriteString(arg759)
		if err761 != nil {
			Usage()
			return
		}
		factory762 := thrift.NewTJSONProtocolFactory()
		jsProt763 := factory762.GetProtocol(mbTrans760)
		argvalue0 := api.NewRelationalQueryRequest()
		err764 := argvalue0.Read(context.Background(), jsProt763)
		if err764 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountRelationalData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "exportRelationalData":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ExportRelationalData requires 1 args")
			flag.Usage()
		}
		arg765 := flag.Arg(1)
		mbTrans766 := thrift.NewTMemoryBufferLen(len(arg765))
		defer mbTrans766.Close()
		_, err767 := mbTrans766.WriteString(arg765)
		if err767 != nil {
			Usage()
			return
		}
		factory768 := thrift.NewTJSONProtocolFactory()
		jsProt769 := factory768.GetProtocol(mbTrans766)
		argvalue0 := api.NewRelationalQueryRequest()
		err770 := argvalue0.Read(context.Background(), jsProt769)
		if err770 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ExportRelationalData(context.Background(), value0))
		fmt.Print("\n")
		break
	case "uploadModel":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "UploadModel requires 3 args")
			flag.Usage()
		}
		argvalue0 := []byte(flag.Arg(1))
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.UploadModel(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "downloadModel":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DownloadModel requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.DownloadModel(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "getModelMeta":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetModelMeta requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetModelMeta(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "saveModelMeta":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveModelMeta requires 1 args")
			flag.Usage()
		}
		arg778 := flag.Arg(1)
		mbTrans779 := thrift.NewTMemoryBufferLen(len(arg778))
		defer mbTrans779.Close()
		_, err780 := mbTrans779.WriteString(arg778)
		if err780 != nil {
			Usage()
			return
		}
		factory781 := thrift.NewTJSONProtocolFactory()
		jsProt782 := factory781.GetProtocol(mbTrans779)
		argvalue0 := api.NewModelMeta()
		err783 := argvalue0.Read(context.Background(), jsProt782)
		if err783 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveModelMeta(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getModelHistory":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetModelHistory requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetModelHistory(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteModel":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DeleteModel requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.DeleteModel(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "getModelTree":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetModelTree requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetModelTree(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryModelArchives":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryModelArchives requires 1 args")
			flag.Usage()
		}
		arg788 := flag.Arg(1)
		mbTrans789 := thrift.NewTMemoryBufferLen(len(arg788))
		defer mbTrans789.Close()
		_, err790 := mbTrans789.WriteString(arg788)
		if err790 != nil {
			Usage()
			return
		}
		factory791 := thrift.NewTJSONProtocolFactory()
		jsProt792 := factory791.GetProtocol(mbTrans789)
		argvalue0 := api.NewModelArchiveQueryRequest()
		err793 := argvalue0.Read(context.Background(), jsProt792)
		if err793 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryModelArchives(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countModelArchives":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountModelArchives requires 1 args")
			flag.Usage()
		}
		arg794 := flag.Arg(1)
		mbTrans795 := thrift.NewTMemoryBufferLen(len(arg794))
		defer mbTrans795.Close()
		_, err796 := mbTrans795.WriteString(arg794)
		if err796 != nil {
			Usage()
			return
		}
		factory797 := thrift.NewTJSONProtocolFactory()
		jsProt798 := factory797.GetProtocol(mbTrans795)
		argvalue0 := api.NewModelArchiveQueryRequest()
		err799 := argvalue0.Read(context.Background(), jsProt798)
		if err799 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountModelArchives(context.Background(), value0))
		fmt.Print("\n")
		break
	case "extractModelFile":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ExtractModelFile requires 1 args")
			flag.Usage()
		}
		arg800 := flag.Arg(1)
		mbTrans801 := thrift.NewTMemoryBufferLen(len(arg800))
		defer mbTrans801.Close()
		_, err802 := mbTrans801.WriteString(arg800)
		if err802 != nil {
			Usage()
			return
		}
		factory803 := thrift.NewTJSONProtocolFactory()
		jsProt804 := factory803.GetProtocol(mbTrans801)
		argvalue0 := api.NewExtractModelFileRequest()
		err805 := argvalue0.Read(context.Background(), jsProt804)
		if err805 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ExtractModelFile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "uploadAlgorithm":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "UploadAlgorithm requires 3 args")
			flag.Usage()
		}
		argvalue0 := []byte(flag.Arg(1))
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.UploadAlgorithm(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "downloadAlgorithm":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DownloadAlgorithm requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.DownloadAlgorithm(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "getAlgorithmMeta":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetAlgorithmMeta requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetAlgorithmMeta(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "saveAlgorithmMeta":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveAlgorithmMeta requires 1 args")
			flag.Usage()
		}
		arg813 := flag.Arg(1)
		mbTrans814 := thrift.NewTMemoryBufferLen(len(arg813))
		defer mbTrans814.Close()
		_, err815 := mbTrans814.WriteString(arg813)
		if err815 != nil {
			Usage()
			return
		}
		factory816 := thrift.NewTJSONProtocolFactory()
		jsProt817 := factory816.GetProtocol(mbTrans814)
		argvalue0 := api.NewAlgorithmMeta()
		err818 := argvalue0.Read(context.Background(), jsProt817)
		if err818 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveAlgorithmMeta(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getAlgorithmHistory":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetAlgorithmHistory requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetAlgorithmHistory(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteAlgorithm":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DeleteAlgorithm requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.DeleteAlgorithm(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "getAlgorithmTree":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetAlgorithmTree requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetAlgorithmTree(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryAlgorithmArchives":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryAlgorithmArchives requires 1 args")
			flag.Usage()
		}
		arg823 := flag.Arg(1)
		mbTrans824 := thrift.NewTMemoryBufferLen(len(arg823))
		defer mbTrans824.Close()
		_, err825 := mbTrans824.WriteString(arg823)
		if err825 != nil {
			Usage()
			return
		}
		factory826 := thrift.NewTJSONProtocolFactory()
		jsProt827 := factory826.GetProtocol(mbTrans824)
		argvalue0 := api.NewAlgorithmArchiveQueryRequest()
		err828 := argvalue0.Read(context.Background(), jsProt827)
		if err828 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryAlgorithmArchives(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countAlgorithmArchives":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountAlgorithmArchives requires 1 args")
			flag.Usage()
		}
		arg829 := flag.Arg(1)
		mbTrans830 := thrift.NewTMemoryBufferLen(len(arg829))
		defer mbTrans830.Close()
		_, err831 := mbTrans830.WriteString(arg829)
		if err831 != nil {
			Usage()
			return
		}
		factory832 := thrift.NewTJSONProtocolFactory()
		jsProt833 := factory832.GetProtocol(mbTrans830)
		argvalue0 := api.NewAlgorithmArchiveQueryRequest()
		err834 := argvalue0.Read(context.Background(), jsProt833)
		if err834 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountAlgorithmArchives(context.Background(), value0))
		fmt.Print("\n")
		break
	case "extractAlgorithmFile":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ExtractAlgorithmFile requires 1 args")
			flag.Usage()
		}
		arg835 := flag.Arg(1)
		mbTrans836 := thrift.NewTMemoryBufferLen(len(arg835))
		defer mbTrans836.Close()
		_, err837 := mbTrans836.WriteString(arg835)
		if err837 != nil {
			Usage()
			return
		}
		factory838 := thrift.NewTJSONProtocolFactory()
		jsProt839 := factory838.GetProtocol(mbTrans836)
		argvalue0 := api.NewExtractAlgorithmFileRequest()
		err840 := argvalue0.Read(context.Background(), jsProt839)
		if err840 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ExtractAlgorithmFile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryDataArchives":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryDataArchives requires 1 args")
			flag.Usage()
		}
		arg841 := flag.Arg(1)
		mbTrans842 := thrift.NewTMemoryBufferLen(len(arg841))
		defer mbTrans842.Close()
		_, err843 := mbTrans842.WriteString(arg841)
		if err843 != nil {
			Usage()
			return
		}
		factory844 := thrift.NewTJSONProtocolFactory()
		jsProt845 := factory844.GetProtocol(mbTrans842)
		argvalue0 := api.NewDataArchiveQueryRequest()
		err846 := argvalue0.Read(context.Background(), jsProt845)
		if err846 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryDataArchives(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getDataArchiveDetail":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDataArchiveDetail requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetDataArchiveDetail(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countDataArchives":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountDataArchives requires 1 args")
			flag.Usage()
		}
		arg848 := flag.Arg(1)
		mbTrans849 := thrift.NewTMemoryBufferLen(len(arg848))
		defer mbTrans849.Close()
		_, err850 := mbTrans849.WriteString(arg848)
		if err850 != nil {
			Usage()
			return
		}
		factory851 := thrift.NewTJSONProtocolFactory()
		jsProt852 := factory851.GetProtocol(mbTrans849)
		argvalue0 := api.NewDataArchiveQueryRequest()
		err853 := argvalue0.Read(context.Background(), jsProt852)
		if err853 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountDataArchives(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteDataArchive":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteDataArchive requires 1 args")
			flag.Usage()
		}
		arg854 := flag.Arg(1)
		mbTrans855 := thrift.NewTMemoryBufferLen(len(arg854))
		defer mbTrans855.Close()
		_, err856 := mbTrans855.WriteString(arg854)
		if err856 != nil {
			Usage()
			return
		}
		factory857 := thrift.NewTJSONProtocolFactory()
		jsProt858 := factory857.GetProtocol(mbTrans855)
		argvalue0 := api.NewDataArchiveQueryRequest()
		err859 := argvalue0.Read(context.Background(), jsProt858)
		if err859 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteDataArchive(context.Background(), value0))
		fmt.Print("\n")
		break
	case "updateDataArchive":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateDataArchive requires 1 args")
			flag.Usage()
		}
		arg860 := flag.Arg(1)
		mbTrans861 := thrift.NewTMemoryBufferLen(len(arg860))
		defer mbTrans861.Close()
		_, err862 := mbTrans861.WriteString(arg860)
		if err862 != nil {
			Usage()
			return
		}
		factory863 := thrift.NewTJSONProtocolFactory()
		jsProt864 := factory863.GetProtocol(mbTrans861)
		argvalue0 := api.NewDataArchive()
		err865 := argvalue0.Read(context.Background(), jsProt864)
		if err865 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateDataArchive(context.Background(), value0))
		fmt.Print("\n")
		break
	case "createProject":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CreateProject requires 1 args")
			flag.Usage()
		}
		arg866 := flag.Arg(1)
		mbTrans867 := thrift.NewTMemoryBufferLen(len(arg866))
		defer mbTrans867.Close()
		_, err868 := mbTrans867.WriteString(arg866)
		if err868 != nil {
			Usage()
			return
		}
		factory869 := thrift.NewTJSONProtocolFactory()
		jsProt870 := factory869.GetProtocol(mbTrans867)
		argvalue0 := api.NewProject()
		err871 := argvalue0.Read(context.Background(), jsProt870)
		if err871 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CreateProject(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryProjects":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryProjects requires 1 args")
			flag.Usage()
		}
		arg872 := flag.Arg(1)
		mbTrans873 := thrift.NewTMemoryBufferLen(len(arg872))
		defer mbTrans873.Close()
		_, err874 := mbTrans873.WriteString(arg872)
		if err874 != nil {
			Usage()
			return
		}
		factory875 := thrift.NewTJSONProtocolFactory()
		jsProt876 := factory875.GetProtocol(mbTrans873)
		argvalue0 := api.NewProjectsQueryRequest()
		err877 := argvalue0.Read(context.Background(), jsProt876)
		if err877 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryProjects(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countProjects":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountProjects requires 1 args")
			flag.Usage()
		}
		arg878 := flag.Arg(1)
		mbTrans879 := thrift.NewTMemoryBufferLen(len(arg878))
		defer mbTrans879.Close()
		_, err880 := mbTrans879.WriteString(arg878)
		if err880 != nil {
			Usage()
			return
		}
		factory881 := thrift.NewTJSONProtocolFactory()
		jsProt882 := factory881.GetProtocol(mbTrans879)
		argvalue0 := api.NewProjectsQueryRequest()
		err883 := argvalue0.Read(context.Background(), jsProt882)
		if err883 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountProjects(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getProject":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetProject requires 1 args")
			flag.Usage()
		}
		argvalue0, err884 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err884 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetProject(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getProjectTree":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetProjectTree requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetProjectTree(context.Background(), value0))
		fmt.Print("\n")
		break
	case "importProject":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "ImportProject requires 2 args")
			flag.Usage()
		}
		argvalue0 := []byte(flag.Arg(1))
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.ImportProject(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "exportProject":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ExportProject requires 1 args")
			flag.Usage()
		}
		arg888 := flag.Arg(1)
		mbTrans889 := thrift.NewTMemoryBufferLen(len(arg888))
		defer mbTrans889.Close()
		_, err890 := mbTrans889.WriteString(arg888)
		if err890 != nil {
			Usage()
			return
		}
		factory891 := thrift.NewTJSONProtocolFactory()
		jsProt892 := factory891.GetProtocol(mbTrans889)
		argvalue0 := api.NewProjectExportRequest()
		err893 := argvalue0.Read(context.Background(), jsProt892)
		if err893 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ExportProject(context.Background(), value0))
		fmt.Print("\n")
		break
	case "saveSimulationArchive":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveSimulationArchive requires 1 args")
			flag.Usage()
		}
		arg894 := flag.Arg(1)
		mbTrans895 := thrift.NewTMemoryBufferLen(len(arg894))
		defer mbTrans895.Close()
		_, err896 := mbTrans895.WriteString(arg894)
		if err896 != nil {
			Usage()
			return
		}
		factory897 := thrift.NewTJSONProtocolFactory()
		jsProt898 := factory897.GetProtocol(mbTrans895)
		argvalue0 := api.NewSimulationArchive()
		err899 := argvalue0.Read(context.Background(), jsProt898)
		if err899 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveSimulationArchive(context.Background(), value0))
		fmt.Print("\n")
		break
	case "querySimulationArchives":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "QuerySimulationArchives requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4) == "true"
		value3 := argvalue3
		tmp4, err904 := (strconv.Atoi(flag.Arg(5)))
		if err904 != nil {
			Usage()
			return
		}
		argvalue4 := int32(tmp4)
		value4 := argvalue4
		tmp5, err905 := (strconv.Atoi(flag.Arg(6)))
		if err905 != nil {
			Usage()
			return
		}
		argvalue5 := int32(tmp5)
		value5 := argvalue5
		fmt.Print(client.QuerySimulationArchives(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "countSimulationArchives":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "CountSimulationArchives requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4) == "true"
		value3 := argvalue3
		fmt.Print(client.CountSimulationArchives(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "getSimulationArchive":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetSimulationArchive requires 1 args")
			flag.Usage()
		}
		argvalue0, err910 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err910 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetSimulationArchive(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteSimulationArchive":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteSimulationArchive requires 1 args")
			flag.Usage()
		}
		argvalue0, err911 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err911 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteSimulationArchive(context.Background(), value0))
		fmt.Print("\n")
		break
	case "validateSimulationArchiveName":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ValidateSimulationArchiveName requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.ValidateSimulationArchiveName(context.Background(), value0))
		fmt.Print("\n")
		break
	case "copySimulationArchive":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "CopySimulationArchive requires 2 args")
			flag.Usage()
		}
		argvalue0, err913 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err913 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.CopySimulationArchive(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "runSimulation":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RunSimulation requires 1 args")
			flag.Usage()
		}
		argvalue0, err915 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err915 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RunSimulation(context.Background(), value0))
		fmt.Print("\n")
		break
	case "runSimulationSelective":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RunSimulationSelective requires 1 args")
			flag.Usage()
		}
		arg916 := flag.Arg(1)
		mbTrans917 := thrift.NewTMemoryBufferLen(len(arg916))
		defer mbTrans917.Close()
		_, err918 := mbTrans917.WriteString(arg916)
		if err918 != nil {
			Usage()
			return
		}
		factory919 := thrift.NewTJSONProtocolFactory()
		jsProt920 := factory919.GetProtocol(mbTrans917)
		argvalue0 := api.NewRunSimulationSelectiveRequest()
		err921 := argvalue0.Read(context.Background(), jsProt920)
		if err921 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RunSimulationSelective(context.Background(), value0))
		fmt.Print("\n")
		break
	case "stopSimulation":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "StopSimulation requires 1 args")
			flag.Usage()
		}
		argvalue0, err922 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err922 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.StopSimulation(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getSimulationExecutionStatus":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetSimulationExecutionStatus requires 1 args")
			flag.Usage()
		}
		argvalue0, err923 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err923 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetSimulationExecutionStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getSimulationExecutionLog":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetSimulationExecutionLog requires 1 args")
			flag.Usage()
		}
		argvalue0, err924 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err924 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.GetSimulationExecutionLog(context.Background(), value0))
		fmt.Print("\n")
		break
	case "querySimulationExecutionRecords":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QuerySimulationExecutionRecords requires 1 args")
			flag.Usage()
		}
		arg925 := flag.Arg(1)
		mbTrans926 := thrift.NewTMemoryBufferLen(len(arg925))
		defer mbTrans926.Close()
		_, err927 := mbTrans926.WriteString(arg925)
		if err927 != nil {
			Usage()
			return
		}
		factory928 := thrift.NewTJSONProtocolFactory()
		jsProt929 := factory928.GetProtocol(mbTrans926)
		argvalue0 := api.NewExecutionRecordQueryRequest()
		err930 := argvalue0.Read(context.Background(), jsProt929)
		if err930 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QuerySimulationExecutionRecords(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countSimulationExecutionRecords":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountSimulationExecutionRecords requires 1 args")
			flag.Usage()
		}
		arg931 := flag.Arg(1)
		mbTrans932 := thrift.NewTMemoryBufferLen(len(arg931))
		defer mbTrans932.Close()
		_, err933 := mbTrans932.WriteString(arg931)
		if err933 != nil {
			Usage()
			return
		}
		factory934 := thrift.NewTJSONProtocolFactory()
		jsProt935 := factory934.GetProtocol(mbTrans932)
		argvalue0 := api.NewExecutionRecordQueryRequest()
		err936 := argvalue0.Read(context.Background(), jsProt935)
		if err936 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountSimulationExecutionRecords(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteSimulationExecutionRecord":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteSimulationExecutionRecord requires 1 args")
			flag.Usage()
		}
		argvalue0, err937 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err937 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.DeleteSimulationExecutionRecord(context.Background(), value0))
		fmt.Print("\n")
		break
	case "uploadSimulationReport":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "UploadSimulationReport requires 2 args")
			flag.Usage()
		}
		argvalue0 := []byte(flag.Arg(1))
		value0 := argvalue0
		argvalue1, err939 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err939 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.UploadSimulationReport(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "simulationPackageDownload":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SimulationPackageDownload requires 1 args")
			flag.Usage()
		}
		argvalue0, err940 := (strconv.ParseInt(flag.Arg(1), 10, 64))
		if err940 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SimulationPackageDownload(context.Background(), value0))
		fmt.Print("\n")
		break
	case "login":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Login requires 1 args")
			flag.Usage()
		}
		arg941 := flag.Arg(1)
		mbTrans942 := thrift.NewTMemoryBufferLen(len(arg941))
		defer mbTrans942.Close()
		_, err943 := mbTrans942.WriteString(arg941)
		if err943 != nil {
			Usage()
			return
		}
		factory944 := thrift.NewTJSONProtocolFactory()
		jsProt945 := factory944.GetProtocol(mbTrans942)
		argvalue0 := api.NewLoginRequest()
		err946 := argvalue0.Read(context.Background(), jsProt945)
		if err946 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.Login(context.Background(), value0))
		fmt.Print("\n")
		break
	case "refreshToken":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "RefreshToken requires 1 args")
			flag.Usage()
		}
		arg947 := flag.Arg(1)
		mbTrans948 := thrift.NewTMemoryBufferLen(len(arg947))
		defer mbTrans948.Close()
		_, err949 := mbTrans948.WriteString(arg947)
		if err949 != nil {
			Usage()
			return
		}
		factory950 := thrift.NewTJSONProtocolFactory()
		jsProt951 := factory950.GetProtocol(mbTrans948)
		argvalue0 := api.NewRefreshTokenRequest()
		err952 := argvalue0.Read(context.Background(), jsProt951)
		if err952 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.RefreshToken(context.Background(), value0))
		fmt.Print("\n")
		break
	case "verifyToken":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "VerifyToken requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.VerifyToken(context.Background(), value0))
		fmt.Print("\n")
		break
	case "logout":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "Logout requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.Logout(context.Background()))
		fmt.Print("\n")
		break
	case "getCurrentAuthUser":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetCurrentAuthUser requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetCurrentAuthUser(context.Background()))
		fmt.Print("\n")
		break
	case "saveUser":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "SaveUser requires 1 args")
			flag.Usage()
		}
		arg954 := flag.Arg(1)
		mbTrans955 := thrift.NewTMemoryBufferLen(len(arg954))
		defer mbTrans955.Close()
		_, err956 := mbTrans955.WriteString(arg954)
		if err956 != nil {
			Usage()
			return
		}
		factory957 := thrift.NewTJSONProtocolFactory()
		jsProt958 := factory957.GetProtocol(mbTrans955)
		argvalue0 := api.NewUser()
		err959 := argvalue0.Read(context.Background(), jsProt958)
		if err959 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.SaveUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "queryUsers":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryUsers requires 1 args")
			flag.Usage()
		}
		arg960 := flag.Arg(1)
		mbTrans961 := thrift.NewTMemoryBufferLen(len(arg960))
		defer mbTrans961.Close()
		_, err962 := mbTrans961.WriteString(arg960)
		if err962 != nil {
			Usage()
			return
		}
		factory963 := thrift.NewTJSONProtocolFactory()
		jsProt964 := factory963.GetProtocol(mbTrans961)
		argvalue0 := api.NewUserQueryRequest()
		err965 := argvalue0.Read(context.Background(), jsProt964)
		if err965 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryUsers(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countUsers":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountUsers requires 1 args")
			flag.Usage()
		}
		arg966 := flag.Arg(1)
		mbTrans967 := thrift.NewTMemoryBufferLen(len(arg966))
		defer mbTrans967.Close()
		_, err968 := mbTrans967.WriteString(arg966)
		if err968 != nil {
			Usage()
			return
		}
		factory969 := thrift.NewTJSONProtocolFactory()
		jsProt970 := factory969.GetProtocol(mbTrans967)
		argvalue0 := api.NewUserQueryRequest()
		err971 := argvalue0.Read(context.Background(), jsProt970)
		if err971 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountUsers(context.Background(), value0))
		fmt.Print("\n")
		break
	case "allUsers":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "AllUsers requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.AllUsers(context.Background()))
		fmt.Print("\n")
		break
	case "getUser":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetUser requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.GetUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "deleteUser":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "DeleteUser requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		fmt.Print(client.DeleteUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "updateUser":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateUser requires 1 args")
			flag.Usage()
		}
		arg974 := flag.Arg(1)
		mbTrans975 := thrift.NewTMemoryBufferLen(len(arg974))
		defer mbTrans975.Close()
		_, err976 := mbTrans975.WriteString(arg974)
		if err976 != nil {
			Usage()
			return
		}
		factory977 := thrift.NewTJSONProtocolFactory()
		jsProt978 := factory977.GetProtocol(mbTrans975)
		argvalue0 := api.NewUser()
		err979 := argvalue0.Read(context.Background(), jsProt978)
		if err979 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateUser(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getRoles":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetRoles requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetRoles(context.Background()))
		fmt.Print("\n")
		break
	case "changePassword":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ChangePassword requires 1 args")
			flag.Usage()
		}
		arg980 := flag.Arg(1)
		mbTrans981 := thrift.NewTMemoryBufferLen(len(arg980))
		defer mbTrans981.Close()
		_, err982 := mbTrans981.WriteString(arg980)
		if err982 != nil {
			Usage()
			return
		}
		factory983 := thrift.NewTJSONProtocolFactory()
		jsProt984 := factory983.GetProtocol(mbTrans981)
		argvalue0 := api.NewChangePasswordRequest()
		err985 := argvalue0.Read(context.Background(), jsProt984)
		if err985 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.ChangePassword(context.Background(), value0))
		fmt.Print("\n")
		break
	case "getCurrentUser":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetCurrentUser requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetCurrentUser(context.Background()))
		fmt.Print("\n")
		break
	case "listOwnerTables":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "ListOwnerTables requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.ListOwnerTables(context.Background()))
		fmt.Print("\n")
		break
	case "queryDataPermissions":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "QueryDataPermissions requires 1 args")
			flag.Usage()
		}
		arg986 := flag.Arg(1)
		mbTrans987 := thrift.NewTMemoryBufferLen(len(arg986))
		defer mbTrans987.Close()
		_, err988 := mbTrans987.WriteString(arg986)
		if err988 != nil {
			Usage()
			return
		}
		factory989 := thrift.NewTJSONProtocolFactory()
		jsProt990 := factory989.GetProtocol(mbTrans987)
		argvalue0 := api.NewDataPermissionQueryRequest()
		err991 := argvalue0.Read(context.Background(), jsProt990)
		if err991 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.QueryDataPermissions(context.Background(), value0))
		fmt.Print("\n")
		break
	case "countDataPermissions":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CountDataPermissions requires 1 args")
			flag.Usage()
		}
		arg992 := flag.Arg(1)
		mbTrans993 := thrift.NewTMemoryBufferLen(len(arg992))
		defer mbTrans993.Close()
		_, err994 := mbTrans993.WriteString(arg992)
		if err994 != nil {
			Usage()
			return
		}
		factory995 := thrift.NewTJSONProtocolFactory()
		jsProt996 := factory995.GetProtocol(mbTrans993)
		argvalue0 := api.NewDataPermissionQueryRequest()
		err997 := argvalue0.Read(context.Background(), jsProt996)
		if err997 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.CountDataPermissions(context.Background(), value0))
		fmt.Print("\n")
		break
	case "updateDataPermission":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "UpdateDataPermission requires 1 args")
			flag.Usage()
		}
		arg998 := flag.Arg(1)
		mbTrans999 := thrift.NewTMemoryBufferLen(len(arg998))
		defer mbTrans999.Close()
		_, err1000 := mbTrans999.WriteString(arg998)
		if err1000 != nil {
			Usage()
			return
		}
		factory1001 := thrift.NewTJSONProtocolFactory()
		jsProt1002 := factory1001.GetProtocol(mbTrans999)
		argvalue0 := api.NewDataPermissionUpdateRequest()
		err1003 := argvalue0.Read(context.Background(), jsProt1002)
		if err1003 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		fmt.Print(client.UpdateDataPermission(context.Background(), value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
