/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tsinghua.thrift.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)", date = "2026-06-23")
public class RunSimulationSelectiveRequest implements org.apache.thrift.TBase<RunSimulationSelectiveRequest, RunSimulationSelectiveRequest._Fields>, java.io.Serializable, Cloneable, Comparable<RunSimulationSelectiveRequest> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RunSimulationSelectiveRequest");

  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField SELECTED_NODE_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("selectedNodeIds", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new RunSimulationSelectiveRequestStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new RunSimulationSelectiveRequestTupleSchemeFactory();

  public long createTime; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> selectedNodeIds; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CREATE_TIME((short)1, "createTime"),
    SELECTED_NODE_IDS((short)2, "selectedNodeIds");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CREATE_TIME
          return CREATE_TIME;
        case 2: // SELECTED_NODE_IDS
          return SELECTED_NODE_IDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CREATETIME_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.SELECTED_NODE_IDS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SELECTED_NODE_IDS, new org.apache.thrift.meta_data.FieldMetaData("selectedNodeIds", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RunSimulationSelectiveRequest.class, metaDataMap);
  }

  public RunSimulationSelectiveRequest() {
  }

  public RunSimulationSelectiveRequest(
    long createTime)
  {
    this();
    this.createTime = createTime;
    setCreateTimeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RunSimulationSelectiveRequest(RunSimulationSelectiveRequest other) {
    __isset_bitfield = other.__isset_bitfield;
    this.createTime = other.createTime;
    if (other.isSetSelectedNodeIds()) {
      java.util.List<java.lang.String> __this__selectedNodeIds = new java.util.ArrayList<java.lang.String>(other.selectedNodeIds);
      this.selectedNodeIds = __this__selectedNodeIds;
    }
  }

  @Override
  public RunSimulationSelectiveRequest deepCopy() {
    return new RunSimulationSelectiveRequest(this);
  }

  @Override
  public void clear() {
    setCreateTimeIsSet(false);
    this.createTime = 0;
    this.selectedNodeIds = null;
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public RunSimulationSelectiveRequest setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  public int getSelectedNodeIdsSize() {
    return (this.selectedNodeIds == null) ? 0 : this.selectedNodeIds.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getSelectedNodeIdsIterator() {
    return (this.selectedNodeIds == null) ? null : this.selectedNodeIds.iterator();
  }

  public void addToSelectedNodeIds(java.lang.String elem) {
    if (this.selectedNodeIds == null) {
      this.selectedNodeIds = new java.util.ArrayList<java.lang.String>();
    }
    this.selectedNodeIds.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getSelectedNodeIds() {
    return this.selectedNodeIds;
  }

  public RunSimulationSelectiveRequest setSelectedNodeIds(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> selectedNodeIds) {
    this.selectedNodeIds = selectedNodeIds;
    return this;
  }

  public void unsetSelectedNodeIds() {
    this.selectedNodeIds = null;
  }

  /** Returns true if field selectedNodeIds is set (has been assigned a value) and false otherwise */
  public boolean isSetSelectedNodeIds() {
    return this.selectedNodeIds != null;
  }

  public void setSelectedNodeIdsIsSet(boolean value) {
    if (!value) {
      this.selectedNodeIds = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((java.lang.Long)value);
      }
      break;

    case SELECTED_NODE_IDS:
      if (value == null) {
        unsetSelectedNodeIds();
      } else {
        setSelectedNodeIds((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CREATE_TIME:
      return getCreateTime();

    case SELECTED_NODE_IDS:
      return getSelectedNodeIds();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CREATE_TIME:
      return isSetCreateTime();
    case SELECTED_NODE_IDS:
      return isSetSelectedNodeIds();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof RunSimulationSelectiveRequest)
      return this.equals((RunSimulationSelectiveRequest)that);
    return false;
  }

  public boolean equals(RunSimulationSelectiveRequest that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_createTime = true;
    boolean that_present_createTime = true;
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    boolean this_present_selectedNodeIds = true && this.isSetSelectedNodeIds();
    boolean that_present_selectedNodeIds = true && that.isSetSelectedNodeIds();
    if (this_present_selectedNodeIds || that_present_selectedNodeIds) {
      if (!(this_present_selectedNodeIds && that_present_selectedNodeIds))
        return false;
      if (!this.selectedNodeIds.equals(that.selectedNodeIds))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createTime);

    hashCode = hashCode * 8191 + ((isSetSelectedNodeIds()) ? 131071 : 524287);
    if (isSetSelectedNodeIds())
      hashCode = hashCode * 8191 + selectedNodeIds.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(RunSimulationSelectiveRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetCreateTime(), other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSelectedNodeIds(), other.isSetSelectedNodeIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSelectedNodeIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.selectedNodeIds, other.selectedNodeIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("RunSimulationSelectiveRequest(");
    boolean first = true;

    sb.append("createTime:");
    sb.append(this.createTime);
    first = false;
    if (isSetSelectedNodeIds()) {
      if (!first) sb.append(", ");
      sb.append("selectedNodeIds:");
      if (this.selectedNodeIds == null) {
        sb.append("null");
      } else {
        sb.append(this.selectedNodeIds);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RunSimulationSelectiveRequestStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RunSimulationSelectiveRequestStandardScheme getScheme() {
      return new RunSimulationSelectiveRequestStandardScheme();
    }
  }

  private static class RunSimulationSelectiveRequestStandardScheme extends org.apache.thrift.scheme.StandardScheme<RunSimulationSelectiveRequest> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, RunSimulationSelectiveRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SELECTED_NODE_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list82 = iprot.readListBegin();
                struct.selectedNodeIds = new java.util.ArrayList<java.lang.String>(_list82.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem83;
                for (int _i84 = 0; _i84 < _list82.size; ++_i84)
                {
                  _elem83 = iprot.readString();
                  struct.selectedNodeIds.add(_elem83);
                }
                iprot.readListEnd();
              }
              struct.setSelectedNodeIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, RunSimulationSelectiveRequest struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
      oprot.writeI64(struct.createTime);
      oprot.writeFieldEnd();
      if (struct.selectedNodeIds != null) {
        if (struct.isSetSelectedNodeIds()) {
          oprot.writeFieldBegin(SELECTED_NODE_IDS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.selectedNodeIds.size()));
            for (java.lang.String _iter85 : struct.selectedNodeIds)
            {
              oprot.writeString(_iter85);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RunSimulationSelectiveRequestTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public RunSimulationSelectiveRequestTupleScheme getScheme() {
      return new RunSimulationSelectiveRequestTupleScheme();
    }
  }

  private static class RunSimulationSelectiveRequestTupleScheme extends org.apache.thrift.scheme.TupleScheme<RunSimulationSelectiveRequest> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RunSimulationSelectiveRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCreateTime()) {
        optionals.set(0);
      }
      if (struct.isSetSelectedNodeIds()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetCreateTime()) {
        oprot.writeI64(struct.createTime);
      }
      if (struct.isSetSelectedNodeIds()) {
        {
          oprot.writeI32(struct.selectedNodeIds.size());
          for (java.lang.String _iter86 : struct.selectedNodeIds)
          {
            oprot.writeString(_iter86);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RunSimulationSelectiveRequest struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.createTime = iprot.readI64();
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list87 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.selectedNodeIds = new java.util.ArrayList<java.lang.String>(_list87.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem88;
          for (int _i89 = 0; _i89 < _list87.size; ++_i89)
          {
            _elem88 = iprot.readString();
            struct.selectedNodeIds.add(_elem88);
          }
        }
        struct.setSelectedNodeIdsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

